import { FormEvent, useEffect, useMemo, useState } from "react";
import { UserPlus, X } from "lucide-react";
import { api, notifyUser } from "../api/client";
import { Patient } from "../types";
import { formatPatientIdentity, formatPatientName } from "../utils/patientIdentity";
import { DateInput } from "./DateInput";

export function QuickPatientModal({initialQuery="",onClose,onCreated}:{initialQuery?:string;onClose:()=>void;onCreated:(patient:Patient)=>void}){
 const parts=useMemo(()=>initialQuery.trim().split(/\s+/).filter(Boolean),[initialQuery]);
 const [form,setForm]=useState({first_name:parts[0]??"",last_name:parts.slice(1).join(" "),date_of_birth:"",oib:"",phone:"",email:"",notes:""});
 const [duplicates,setDuplicates]=useState<Patient[]>([]),[confirmed,setConfirmed]=useState(false);
 const duplicatePath=useMemo(()=>form.first_name.trim()&&form.last_name.trim()?`/api/patients/possible-duplicates?first_name=${encodeURIComponent(form.first_name.trim())}&last_name=${encodeURIComponent(form.last_name.trim())}${form.date_of_birth?`&date_of_birth=${form.date_of_birth}`:""}${form.oib?`&oib=${encodeURIComponent(form.oib)}`:""}`:"",[form.first_name,form.last_name,form.date_of_birth,form.oib]);
 useEffect(()=>{let alive=true;setConfirmed(false);if(!duplicatePath){setDuplicates([]);return}api<Patient[]>(duplicatePath).then(rows=>alive&&setDuplicates(rows)).catch(()=>alive&&setDuplicates([]));return()=>{alive=false}},[duplicatePath]);
 async function submit(e:FormEvent){e.preventDefault();if(form.oib&&!/^\d{11}$/.test(form.oib)){notifyUser("OIB mora imati točno 11 znamenki.","error");return}if(duplicates.length&&!confirmed){notifyUser("Provjerite moguće duplikate prije spremanja.","error");return}const optional=(v:string)=>v.trim()||null;const patient=await api<Patient>("/api/patients",{method:"POST",body:JSON.stringify({...form,first_name:form.first_name.trim(),last_name:form.last_name.trim(),date_of_birth:form.date_of_birth||null,oib:optional(form.oib),phone:optional(form.phone),email:optional(form.email),notes:optional(form.notes)})});onCreated(patient)}
 return <div className="modal-backdrop quick-patient-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal-panel quick-patient-modal" onSubmit={submit}><header><div><span className="eyebrow">Baza pacijenata</span><h2>Dodaj pacijenta</h2><p>Provjerite identitet prije spremanja novog pacijenta.</p></div><button type="button" onClick={onClose}><X size={19}/></button></header>{duplicates.length>0&&<div className="duplicate-warning"><strong>Mogući duplikati</strong>{duplicates.map(p=><span key={p.id}>{formatPatientName(p)} <small>{formatPatientIdentity(p)}</small></span>)}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Provjereno, ipak dodaj novog pacijenta.</label></div>}<div className="quick-patient-grid"><label>Ime<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Prezime<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Datum rođenja<DateInput value={form.date_of_birth} onChange={value=>setForm({...form,date_of_birth:value})}/></label><label>OIB<input inputMode="numeric" value={form.oib} onChange={e=>setForm({...form,oib:e.target.value})}/></label><label>Telefon<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>E-pošta<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="wide-field">Napomena<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><footer><button type="button" onClick={onClose}>Odustani</button><button className="primary"><UserPlus size={17}/> Spremi i odaberi</button></footer></form></div>
}
