/* eslint-disable */
/* Generated by scripts/generate_openapi_types.py. Do not edit manually. */

export type ActivityRequirementUpdate = {
  note?: string | null;
  state: string;
};

export type ApiKeyCreate = {
  expires_at?: string | null;
  name: string;
  scopes: Array<string>;
};

export type ApiKeyCreated = {
  active: boolean;
  clinic_id?: number | null;
  expires_at: string | null;
  id: number;
  institution_id?: number | null;
  key: string;
  name: string;
  scopes: Array<string>;
};

export type ApiKeyOut = {
  active: boolean;
  clinic_id?: number | null;
  created_at: string;
  expires_at: string | null;
  id: number;
  institution_id?: number | null;
  last_used_at?: string | null;
  name: string;
  scopes: Array<string>;
  updated_at: string;
};

export type AppointmentClinicSummary = {
  id?: number | null;
  name?: string | null;
};

export type AppointmentCreate = {
  date: string;
  duration_minutes: number;
  end_time: string;
  episode_id?: number | null;
  notes?: string | null;
  patient_id: number;
  provider_id: number;
  room_id: number;
  service_id: number;
  source?: string;
  start_time: string;
  status?: string;
};

export type AppointmentMaterialConsumptionLine = {
  inventory_item_id: number;
  quantity: number | string;
  reason?: string | null;
};

export type AppointmentMaterialConsumptionRequest = {
  allow_missing_optional?: boolean;
  lines?: Array<AppointmentMaterialConsumptionLine> | null;
};

export type AppointmentOut = {
  arrived_at?: string | null;
  created_at: string;
  date: string;
  duration_minutes: number;
  end_time: string;
  episode?: ClinicalEpisodeOut | null;
  episode_id?: number | null;
  id: number;
  identity_verified_at?: string | null;
  identity_verified_by?: number | null;
  notes?: string | null;
  patient?: PatientOut | null;
  patient_id: number;
  provider?: ProviderOut | null;
  provider_id: number;
  room?: RoomOut | null;
  room_id: number;
  service?: ServiceOut | null;
  service_id: number;
  source?: string;
  start_time: string;
  status?: string;
  updated_at: string;
};

export type AppointmentUpdate = {
  date?: string | null;
  duration_minutes?: number | null;
  end_time?: string | null;
  episode_id?: number | null;
  notes?: string | null;
  patient_id?: number | null;
  provider_id?: number | null;
  room_id?: number | null;
  service_id?: number | null;
  source?: string | null;
  start_time?: string | null;
  status?: string | null;
};

export type BlockerCreate = {
  blocker_key: string;
  category: string;
  details?: string | null;
  is_clinical?: boolean;
  title: string;
};

export type BlockerResolve = {
  resolution_note: string;
};

export type Body_ingest_document_api_patient_journeys__journey_id__documents_ingest_post = {
  document_date?: string | null;
  document_type?: string;
  file: string;
  title: string;
  upload_channel?: string;
};

export type BrowserSessionResponse = {
  csrf_token: string;
  expires_at: string;
  user: {
};
};

export type CheckInItemOut = {
  activity_ids_json?: Array<number>;
  category: string;
  details_json?: {
};
  id: number;
  item_key: string;
  label: string;
  medical_disposition?: string | null;
  medical_disposition_note?: string | null;
  medical_reviewed_at?: string | null;
  note: string | null;
  position: number;
  requires_clinician: boolean;
  state: string;
};

export type CheckInItemUpdate = {
  note?: string | null;
  state: string;
};

export type CheckInMedicalDisposition = {
  disposition: string;
  note: string;
};

export type CheckInOut = {
  arrived_at: string | null;
  completed_at: string | null;
  id: number;
  items: Array<CheckInItemOut>;
  journey_id: number;
  reception_note?: string | null;
  status: string;
};

export type ClinicAuditEventOut = {
  action: string;
  actor_name: string | null;
  actor_type: string;
  actor_user_id: number | null;
  changed_fields: Array<string>;
  clinic_id: number;
  created_at: string;
  entity_id: number | null;
  entity_type: string;
  id: number;
  institution_id: number | null;
  reason_code: string | null;
  request_id: string | null;
  result: string;
  scope_label: string;
  scope_type: string;
  status: string | null;
};

export type ClinicCreate = {
  name: string;
  timezone?: string;
};

export type ClinicOut = {
  active: boolean;
  created_at: string;
  id: number;
  institution_id?: number | null;
  institution_key?: string;
  name: string;
  timezone?: string;
  updated_at: string;
  visible_in_catalog?: boolean;
};

export type ClinicalDecisionTimelineItem = {
  action: string;
  created_at: string;
  id: number;
  label: string;
  source?: string | null;
  summary?: string | null;
};

export type ClinicalDocumentAddendumCreate = {
  content: string;
  reason: string;
};

export type ClinicalDocumentAddendumOut = {
  author_user_id: number;
  clinic_id?: number | null;
  content: string;
  created_at: string;
  id: number;
  institution_id?: number | null;
  original_document_id: number;
  original_document_type?: string;
  patient_id?: number | null;
  reason: string;
  signed_at?: string | null;
  signed_by_user_id?: number | null;
  signed_report_id?: number | null;
  status: string;
  updated_at: string;
};

export type ClinicalDocumentClassificationReview = {
  note?: string | null;
  record_classification: string;
};

export type ClinicalDocumentCreate = {
  ai_summary?: string | null;
  appointment_id?: number | null;
  attachment_path?: string | null;
  author?: string | null;
  clinic_id?: number | null;
  document_date?: string | null;
  document_type?: string;
  institution?: string | null;
  key_findings?: Array<string> | null;
  origin?: string | null;
  patient_id: number;
  raw_text?: string | null;
  recommendations?: Array<string> | null;
  source_type?: string;
  title: string;
};

export type ClinicalDocumentOut = {
  ai_extraction_generated_at?: string | null;
  ai_extraction_status: string;
  ai_extraction_updated_at?: string | null;
  ai_summary?: string | null;
  appointment_id?: number | null;
  attachment_path?: string | null;
  author?: string | null;
  author_professional_role?: string | null;
  author_user_id?: number | null;
  can_add_addendum?: boolean;
  can_edit?: boolean;
  can_review?: boolean;
  clinic_id?: number | null;
  created_at: string;
  document_date?: string | null;
  document_type?: string;
  id: number;
  institution?: string | null;
  is_clinical_record?: boolean;
  key_findings?: Array<string> | null;
  origin?: string | null;
  patient?: PatientOut | null;
  patient_id: number;
  physician_reviewed: boolean;
  raw_text?: string | null;
  recommendations?: Array<string> | null;
  record_classification?: string;
  review_status: string;
  reviewed_at?: string | null;
  reviewed_by?: number | null;
  source_type?: string;
  title: string;
  updated_at: string;
};

export type ClinicalDocumentUpdate = {
  ai_summary?: string | null;
  appointment_id?: number | null;
  attachment_path?: string | null;
  author?: string | null;
  clinic_id?: number | null;
  document_date?: string | null;
  document_type?: string | null;
  institution?: string | null;
  key_findings?: Array<string> | null;
  origin?: string | null;
  patient_id?: number | null;
  raw_text?: string | null;
  recommendations?: Array<string> | null;
  source_type?: string | null;
  title?: string | null;
};

export type ClinicalDocumentUpload = {
  appointment_id?: number | null;
  attachment_name?: string | null;
  author?: string | null;
  clinic_id?: number | null;
  document_date?: string | null;
  document_type?: string;
  institution?: string | null;
  origin?: string | null;
  patient_id: number;
  raw_text?: string | null;
  source_type?: string;
  title: string;
};

export type ClinicalEpisodeCreate = {
  clinical_notes?: string | null;
  end_date?: string | null;
  episode_type?: string;
  owner_provider_id?: number | null;
  patient_id: number;
  priority?: string;
  start_date: string;
  status?: string;
  summary?: string | null;
  title: string;
};

export type ClinicalEpisodeOut = {
  appointment_count?: number | null;
  clinical_notes?: string | null;
  created_at: string;
  created_by?: number | null;
  end_date?: string | null;
  episode_type?: string;
  id: number;
  owner_provider?: ProviderOut | null;
  owner_provider_id?: number | null;
  patient?: PatientOut | null;
  patient_id: number;
  priority?: string;
  start_date: string;
  status?: string;
  summary?: string | null;
  title: string;
  updated_at: string;
};

export type ClinicalEpisodeUpdate = {
  clinical_notes?: string | null;
  end_date?: string | null;
  episode_type?: string | null;
  owner_provider_id?: number | null;
  priority?: string | null;
  start_date?: string | null;
  status?: string | null;
  summary?: string | null;
  title?: string | null;
};

export type ClinicalEvidenceTimelineEventPreview = {
  created_at: string;
  display_timestamp: string;
  event_key: string;
  event_timestamp: string;
  event_type: string;
  is_decision?: boolean;
  label: string;
  limitations?: Array<string>;
  no_decision_disclaimer?: string;
  requires_review?: boolean;
  source_reference: ClinicalEvidenceTimelineSourceReference;
};

export type ClinicalEvidenceTimelineItem = {
  action: string;
  actor_api_key_id?: number | null;
  actor_type?: string | null;
  actor_user_id?: number | null;
  clinical_event_category: string;
  clinical_event_label: string;
  created_at: string;
  id: number;
  is_clinical_evidence_event: boolean;
  knowledge_impact: string;
  message?: string | null;
  object_id?: number | null;
  object_type: string;
};

export type ClinicalEvidenceTimelineListResponse = {
  count: number;
  events: Array<ClinicalEvidenceTimelineEventPreview>;
  is_read_only?: boolean;
  patient_id: number;
  warning?: string;
};

export type ClinicalEvidenceTimelineSourceReference = {
  limitations?: Array<string>;
  patient_id: number;
  provenance_label: string;
  source_document_reference?: string | null;
  source_label: string;
  source_object_reference: string;
  source_object_type: string;
};

export type ClinicalFindingDetailResponse = {
  category: string;
  created_at: string;
  finding_key: string;
  id: number;
  label: string;
  lifecycle_status: string;
  limitations?: Array<string>;
  patient_id: number;
  requires_review: boolean;
  reviewed_at?: string | null;
  reviewed_by_user_id?: number | null;
  safe_disclaimer?: string;
  schema_version: string;
  source_document_id?: number | null;
  source_label: string;
  source_reference: string;
  source_type: string;
  updated_at: string;
  warning?: string;
};

export type ClinicalFindingListResponse = {
  count: number;
  findings: Array<ClinicalFindingReadItem>;
  is_read_only?: boolean;
  patient_id: number;
  warning?: string;
};

export type ClinicalFindingReadItem = {
  category: string;
  created_at: string;
  finding_key: string;
  id: number;
  label: string;
  lifecycle_status: string;
  limitations?: Array<string>;
  patient_id: number;
  requires_review: boolean;
  reviewed_at?: string | null;
  reviewed_by_user_id?: number | null;
  safe_disclaimer?: string;
  schema_version: string;
  source_document_id?: number | null;
  source_label: string;
  source_reference: string;
  source_type: string;
  updated_at: string;
};

export type ClinicalFormCompleteRequest = {
  data?: {
};
  expected_instance_id: number;
  expected_revision_number: number;
  idempotency_key: string;
};

export type ClinicalFormDataUpdate = {
  data?: {
};
  expected_instance_id: number;
  expected_revision_number: number;
};

export type ClinicalFormDefinitionOut = {
  active: boolean;
  activity_kind: string;
  description: string | null;
  form_key: string;
  id: number;
  name: string;
  specialty_key: string;
};

export type ClinicalFormInstanceOut = {
  activity_id: number;
  amended_from_instance_id: number | null;
  binding_source: string;
  completed_at: string | null;
  completed_by: number | null;
  data_json: {
};
  form_version: ClinicalFormVersionOut;
  form_version_id: number;
  id: number;
  purpose: string;
  rendered_summary: string | null;
  resolved_at: string;
  revision_number: number;
  signed_at: string | null;
  signed_by: number | null;
  status: string;
  updated_at: string;
};

export type ClinicalFormVersionOut = {
  approved_at: string | null;
  approved_by: number | null;
  definition_id: number;
  id: number;
  output_document_type: string;
  print_layout_json: {
};
  published_at: string | null;
  sections_json: Array<unknown>;
  status: string;
  validation_schema_json: {
};
  version: number;
};

export type ClinicalOpenQuestionDetailResponse = {
  created_at: string;
  finding_id?: number | null;
  id: number;
  label: string;
  limitations?: Array<string>;
  linked_finding_key?: string | null;
  no_decision_disclaimer?: string;
  patient_id: number;
  question_key: string;
  requires_clinician_review: boolean;
  review_note?: string | null;
  reviewed_at?: string | null;
  reviewed_by_user_id?: number | null;
  source_label: string;
  source_reference: string;
  source_reference_summary: string;
  source_type: string;
  status: string;
  updated_at: string;
  warning?: string;
};

export type ClinicalOpenQuestionListResponse = {
  count: number;
  is_read_only?: boolean;
  patient_id: number;
  questions: Array<ClinicalOpenQuestionReadItem>;
  warning?: string;
};

export type ClinicalOpenQuestionReadItem = {
  created_at: string;
  finding_id?: number | null;
  id: number;
  label: string;
  limitations?: Array<string>;
  no_decision_disclaimer?: string;
  patient_id: number;
  question_key: string;
  requires_clinician_review: boolean;
  reviewed_at?: string | null;
  reviewed_by_user_id?: number | null;
  source_label: string;
  source_reference_summary: string;
  source_type: string;
  status: string;
  updated_at: string;
};

export type ClinicalPlanGenerate = {
  appointment_id?: number | null;
  episode_goal?: string | null;
  findings?: string | null;
  pathology_ordered?: boolean;
  physician_conclusion?: string | null;
  procedure_type?: string | null;
};

export type ClinicalPlanOut = {
  ai_confidence?: string | null;
  confirmed_at?: string | null;
  confirmed_by?: number | null;
  created_at: string;
  due_date?: string | null;
  episode_id: number;
  id: number;
  next_action: string;
  physician_conclusion?: string | null;
  physician_confirmed: boolean;
  priority: string;
  proposed_episode_status?: string | null;
  rationale?: string | null;
  source: string;
  status: string;
  suggested_follow_up?: string | null;
  updated_at: string;
};

export type ClinicalPlanUpdate = {
  due_date?: string | null;
  next_action?: string | null;
  physician_conclusion?: string | null;
  priority?: string | null;
  proposed_episode_status?: string | null;
  rationale?: string | null;
  suggested_follow_up?: string | null;
};

export type ClinicalReadinessAcknowledgmentDetailResponse = {
  acknowledgment_key: string;
  actor_role: string;
  actor_user_id: number;
  advisory_signal_key: string;
  appointment_id: number;
  created_at: string;
  id: number;
  is_clearance?: boolean;
  is_decision?: boolean;
  is_override?: boolean;
  limitations: Array<string>;
  patient_id: number;
  reason: string;
  safe_disclaimer: string;
  schema_version: string;
  snapshot_id?: number | null;
  warning: string;
};

export type ClinicalReadinessAcknowledgmentListResponse = {
  acknowledgments: Array<ClinicalReadinessAcknowledgmentReadItem>;
  appointment_id: number;
  count: number;
  is_read_only: boolean;
  warning: string;
};

export type ClinicalReadinessAcknowledgmentReadItem = {
  acknowledgment_key: string;
  actor_role: string;
  actor_user_id: number;
  advisory_signal_key: string;
  appointment_id: number;
  created_at: string;
  id: number;
  is_clearance?: boolean;
  is_decision?: boolean;
  is_override?: boolean;
  limitations: Array<string>;
  patient_id: number;
  reason: string;
  safe_disclaimer: string;
  schema_version: string;
  snapshot_id?: number | null;
};

export type ClinicalReadinessPreviewItem = {
  audit_required: boolean;
  blocking: boolean;
  category: string;
  key: string;
  label: string;
  override_allowed: boolean;
  override_reason_required: boolean;
  override_role?: string | null;
  responsible_role?: string | null;
  severity: string;
  source_label?: string | null;
  source_ref?: string | null;
  source_type: string;
  status: string;
  suggested_action?: string | null;
};

export type ClinicalReadinessPreviewResponse = {
  appointment_id: number;
  generated_at: string;
  is_preview: boolean;
  items: Array<ClinicalReadinessPreviewItem>;
  limitations: Array<string>;
  patient_id: number | null;
  service_id: number | null;
  snapshot_status: string;
  snapshot_supported: boolean;
  snapshot_warning: string;
  source_warnings: Array<string>;
  status: string;
  summary: string;
  template_binding_status: string;
  template_binding_warning?: string | null;
  template_key?: string | null;
  template_label?: string | null;
  template_version?: string | null;
  template_version_warning?: string | null;
};

export type ClinicalReadinessSnapshotCaptureRequest = {
  client_preview_generated_at?: string | null;
  idempotency_key?: string | null;
  reason: string;
};

export type ClinicalReadinessSnapshotDetailResponse = {
  appointment_id: number;
  created_at: string;
  created_by_user_id: number;
  disclaimer: string;
  id: number;
  is_preview_snapshot: boolean;
  items: Array<{
}>;
  limitations: Array<string>;
  patient_id: number;
  preview_generated_at: string;
  preview_status: string;
  preview_summary: string;
  schema_version: string;
  service_id: number;
  snapshot_reason: string;
  source_refs: Array<{
}>;
  source_warnings: Array<string>;
  superseded_at?: string | null;
  superseded_by_snapshot_id?: number | null;
  superseded_reason?: string | null;
  template_binding_status?: string | null;
  template_binding_warning?: string | null;
  template_key?: string | null;
  template_label?: string | null;
  template_version?: string | null;
  warning: string;
};

export type ClinicalReadinessSnapshotHistoryItem = {
  appointment_id: number;
  created_at: string;
  created_by_user_id: number;
  disclaimer: string;
  id: number;
  is_preview_snapshot: boolean;
  item_count: number;
  limitation_count: number;
  patient_id: number;
  preview_generated_at: string;
  preview_status: string;
  schema_version: string;
  service_id: number;
  snapshot_reason: string;
  source_warning_count: number;
  superseded_at?: string | null;
  superseded_by_snapshot_id?: number | null;
  superseded_reason?: string | null;
  template_binding_status?: string | null;
  template_key?: string | null;
  template_label?: string | null;
  template_version?: string | null;
};

export type ClinicalReadinessSnapshotHistoryResponse = {
  appointment_id: number;
  count: number;
  is_preview_history: boolean;
  snapshots: Array<ClinicalReadinessSnapshotHistoryItem>;
  warning: string;
};

export type ClinicalReadinessSnapshotResponse = {
  appointment_id: number;
  created_at: string;
  created_by_user_id: number;
  disclaimer: string;
  id: number;
  is_preview_snapshot: boolean;
  items: Array<{
}>;
  limitations: Array<string>;
  patient_id: number;
  preview_generated_at: string;
  preview_status: string;
  schema_version: string;
  service_id: number;
  snapshot_reason: string;
  source_refs: Array<{
}>;
  source_warnings: Array<string>;
  template_binding_status?: string | null;
  template_key?: string | null;
  template_label?: string | null;
  template_version?: string | null;
};

export type ClinicalReadinessSnapshotSupersedeRequest = {
  reason: string;
};

export type ClinicalReadinessSnapshotSupersedeResponse = {
  new_snapshot: ClinicalReadinessSnapshotResponse;
  old_snapshot_id: number;
  superseded_at: string;
  superseded_reason: string;
  warning: string;
};

export type ClosureOut = {
  billing_status: string;
  consumables?: Array<{
}>;
  consumables_status: string;
  invoice?: {
} | null;
  journey_id: number;
  payment_status: string;
  stage: string;
};

export type CommunicationOut = {
  channel: string;
  correlation_id: string;
  delivered_at: string | null;
  failure_reason: string | null;
  id: number;
  journey_id: number;
  scheduled_at: string | null;
  sent_at: string | null;
  status: string;
  template_key: string;
};

export type ConsumableLine = {
  inventory_item_id: number;
  quantity: number | string;
  reason?: string | null;
  serial_number?: string | null;
};

export type ConsumablesConfirm = {
  lines?: Array<ConsumableLine>;
  not_applicable?: boolean;
};

export type DailyDashboardActivity = {
  clinician_name?: string | null;
  end_time: string;
  id: number;
  room_name?: string | null;
  sequence: number;
  service_name: string;
  status: string;
  time: string;
};

export type DailyDashboardBlocker = {
  details?: string | null;
  id: number;
  is_clinical?: boolean;
  title: string;
};

export type DailyDashboardClinic = {
  id: number;
  name: string;
};

export type DailyDashboardOperationalReason = {
  code: string;
  label: string;
};

export type DailyDashboardResponse = {
  available_clinics?: Array<DailyDashboardClinic>;
  can_filter_clinician?: boolean;
  date: string;
  refreshed_at: string;
  rows: Array<DailyDashboardRow>;
  scope: string;
  scope_label: string;
  scoped_clinician_id?: number | null;
  viewer_role: string;
  visible_sections: Array<string>;
};

export type DailyDashboardRow = {
  activities?: Array<DailyDashboardActivity>;
  activity_count?: number;
  allowed_actions?: Array<string>;
  appointment_id: number;
  arrival_status: string;
  billing_status: string;
  blocker_labels?: Array<string>;
  blocker_status: string;
  blockers?: Array<DailyDashboardBlocker>;
  check_in_status: string;
  clinic_id?: number | null;
  clinic_name?: string | null;
  clinician_id: number;
  clinician_name: string;
  consumables_status: string;
  current_activity_id?: number | null;
  document_status: string;
  encounter_status: string;
  intake_channel: string;
  journey_id: number;
  next_activity_id?: number | null;
  operational_status: string;
  operational_status_label: string;
  operational_status_reasons?: Array<DailyDashboardOperationalReason>;
  operational_status_severity: string;
  patient_date_of_birth: string | null;
  patient_id: number;
  patient_name: string;
  payment_status: string;
  preparation_status: string;
  reception_warning?: boolean;
  reception_warning_details?: Array<string>;
  room_id: number;
  room_name: string;
  service_id: number;
  service_name: string;
  time: string;
  workflow_stage: string;
};

export type DeferPayment = {
  reason: string;
};

export type DemoPersonaSessionRequest = {
  persona_key: 'admin' | 'receptionist' | 'nurse' | 'physician_1' | 'physician_2';
};

export type DemoPersonaSessionResponse = {
  csrf_token: string;
  expires_at: string;
  persona_key: string;
  user: {
};
};

export type DiagnosisSuggestion = {
  code: string;
  title: string;
};

export type DiagnosisSuggestionDecision = {
  action: 'accept' | 'reject';
  code: string;
  model: string;
  provider?: 'openai';
  request_id: string;
  title: string;
};

export type DiagnosisSuggestionRequest = {
  anamnesis?: string | null;
  examination?: string | null;
  opinion?: string | null;
  patient_findings?: string | null;
};

export type DiagnosisSuggestionsOut = {
  diagnoses: Array<DiagnosisSuggestion>;
  disclaimer?: string;
  generated_at: string;
  model: string;
  provider?: 'openai';
  request_id: string;
};

export type DocumentIngestionOut = {
  checksum_sha256: string | null;
  classification_confidence: string | null;
  clinical_episode_id: number | null;
  document_type: string;
  extraction_confidence: string | null;
  file_size_bytes: number | null;
  id: number;
  is_clinical_record: boolean;
  journey_id: number | null;
  lifecycle_status: string;
  mime_type: string | null;
  ocr_text: string | null;
  original_filename: string | null;
  patient_id: number;
  received_at: string | null;
  record_classification: string;
  review_status: string;
  title: string;
  upload_channel: string | null;
};

export type DocumentJobOut = {
  attempts: number;
  clinical_document_id: number;
  completed_at: string | null;
  error_message: string | null;
  id: number;
  job_type: string;
  provider: string;
  queued_at: string;
  result_metadata_json: {
} | null;
  started_at: string | null;
  status: string;
};

export type DocumentRequestCreate = {
  document_type: string;
  mandatory?: boolean;
  title: string;
};

export type EncounterOut = {
  anamnesis?: string | null;
  clinical_episode_id: number | null;
  completed_at: string | null;
  completed_by: number | null;
  created_at: string;
  diagnosis?: string | null;
  examination?: string | null;
  follow_up_plan?: string | null;
  id: number;
  journey_id: number;
  opened_at: string;
  opened_by: number | null;
  opinion?: string | null;
  patient_findings?: string | null;
  procedure_findings?: string | null;
  recommendations?: string | null;
  status: string;
  treatment?: string | null;
  updated_at: string;
};

export type EncounterUpdate = {
  anamnesis?: string | null;
  diagnosis?: string | null;
  examination?: string | null;
  follow_up_plan?: string | null;
  opinion?: string | null;
  patient_findings?: string | null;
  procedure_findings?: string | null;
  recommendations?: string | null;
  treatment?: string | null;
};

export type ErrorResponse = {
  detail: string;
};

export type FormAnswer = {
  answers_json: {
};
};

export type FormBindingCreate = {
  activity_kind?: string | null;
  clinic_id?: number | null;
  form_version_id: number;
  service_id?: number | null;
  specialty_key?: string | null;
};

export type FormDefinitionCreate = {
  activity_kind: string;
  description?: string | null;
  form_key: string;
  name: string;
  output_document_type: string;
  print_layout_json?: {
};
  sections_json: Array<unknown>;
  specialty_key: string;
  validation_schema_json?: {
};
};

export type FormRequest = {
  template_id: number;
};

export type FormTemplateCreate = {
  approved?: boolean;
  fields_json?: Array<{
}>;
  name: string;
  template_key: string;
  version: string;
};

export type FormTemplateOut = {
  active: boolean;
  approved_at: string | null;
  fields_json: Array<unknown>;
  id: number;
  name: string;
  template_key: string;
  version: string;
};

export type FormVersionDraftCreate = {
  output_document_type?: string | null;
  print_layout_json?: {
} | null;
  sections_json?: Array<unknown> | null;
  validation_schema_json?: {
} | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type InterventionCreate = {
  anatomical_site?: string | null;
  complication?: string | null;
  count?: number;
  description?: string | null;
  device?: string | null;
  intervention_type: string;
  retrieval_status?: string | null;
  size?: string | null;
  technique?: string | null;
};

export type InterventionOut = {
  activity_id: number;
  anatomical_site?: string | null;
  complication?: string | null;
  count?: number;
  created_at: string;
  created_by: number | null;
  description?: string | null;
  device?: string | null;
  id: number;
  intervention_type: string;
  retrieval_status?: string | null;
  size?: string | null;
  technique?: string | null;
};

export type InventoryBatchCreate = {
  expiration_date?: string | null;
  inventory_item_id: number;
  location_id: number;
  lot_number?: string | null;
  purchase_price?: number | string;
  quantity: number | string;
  supplier_id?: number | null;
};

export type InventoryBatchOut = {
  created_at: string;
  expiration_date?: string | null;
  id: number;
  inventory_item_id: number;
  location_id: number;
  lot_number?: string | null;
  purchase_price?: string;
  quantity: string;
  supplier_id?: number | null;
  updated_at: string;
};

export type InventoryItemCreate = {
  active?: boolean;
  category?: string | null;
  current_stock?: number | string;
  expiration_tracking_enabled?: boolean;
  lot_tracking_enabled?: boolean;
  minimum_stock?: number | string;
  name: string;
  purchase_price?: number | string;
  reorder_point?: number | string;
  selling_price?: number | string;
  sku: string;
  supplier_id?: number | null;
  unit_of_measure?: string;
};

export type InventoryItemOut = {
  active?: boolean;
  category?: string | null;
  created_at: string;
  current_stock?: string;
  expiration_tracking_enabled?: boolean;
  id: number;
  lot_tracking_enabled?: boolean;
  minimum_stock?: string;
  name: string;
  purchase_price?: string;
  reorder_point?: string;
  selling_price?: string;
  sku: string;
  supplier_id?: number | null;
  unit_of_measure?: string;
  updated_at: string;
};

export type InvoiceCreate = {
  appointment_id?: number | null;
  business_unit?: string | null;
  fiscalization_message?: string | null;
  fiscalization_provider?: string | null;
  fiscalization_reference?: string | null;
  fiscalization_status?: string | null;
  fiscalized_at?: string | null;
  invoice_date?: string | null;
  invoice_number?: string | null;
  notes?: string | null;
  operator?: string | null;
  patient_id: number;
  payment_method?: string | null;
  payment_status?: string;
  register_id?: string | null;
  status?: string;
  total_amount?: number | string;
  vat_id?: string | null;
};

export type InvoiceIssueOut = {
  appointment_id?: number | null;
  business_unit?: string | null;
  created_at: string;
  fiscalization_message?: string | null;
  fiscalization_provider?: string | null;
  fiscalization_reference?: string | null;
  fiscalization_status?: string | null;
  fiscalized_at?: string | null;
  id: number;
  invoice_date?: string | null;
  invoice_number?: string | null;
  lines?: Array<InvoiceLineOut>;
  notes?: string | null;
  operator?: string | null;
  patient_id: number;
  payment_method?: string | null;
  payment_status?: string;
  payments?: Array<PaymentTransactionOut>;
  register_id?: string | null;
  status?: string;
  total_amount?: string;
  updated_at: string;
  vat_id?: string | null;
};

export type InvoiceLineCreate = {
  description: string;
  inventory_item_id?: number | null;
  quantity?: number | string;
  service_id?: number | null;
  unit_price?: number | string;
  vat_rate?: number | string;
};

export type InvoiceLineOut = {
  description: string;
  id: number;
  inventory_item_id?: number | null;
  invoice_id: number;
  quantity?: string;
  service_id?: number | null;
  total: string;
  unit_price?: string;
  vat_rate?: string;
};

export type InvoiceLineUpdate = {
  description?: string | null;
  inventory_item_id?: number | null;
  quantity?: number | string | null;
  service_id?: number | null;
  unit_price?: number | string | null;
  vat_rate?: number | string | null;
};

export type InvoiceOperationalListItemOut = {
  can_issue: boolean;
  can_record_payment: boolean;
  id: number;
  invoice_date: string;
  invoice_number: string;
  outstanding_amount: string;
  paid_amount: string;
  patient_id: number;
  patient_name: string;
  payment_count: number;
  payment_status: string;
  status: string;
  total_amount: string;
};

export type InvoiceOut = {
  appointment_id?: number | null;
  business_unit?: string | null;
  created_at: string;
  fiscalization_message?: string | null;
  fiscalization_provider?: string | null;
  fiscalization_reference?: string | null;
  fiscalization_status?: string | null;
  fiscalized_at?: string | null;
  id: number;
  invoice_date?: string | null;
  invoice_number?: string | null;
  lines?: Array<InvoiceLineOut>;
  notes?: string | null;
  operator?: string | null;
  patient_id: number;
  payment_method?: string | null;
  payment_status?: string;
  payments?: Array<PaymentTransactionOut>;
  register_id?: string | null;
  status?: string;
  total_amount?: string;
  updated_at: string;
  vat_id?: string | null;
};

export type JourneyActivityCreate = {
  activity_key: string;
  activity_kind?: string;
  date: string;
  depends_on_activity_id?: number | null;
  end_time: string;
  notes?: string | null;
  provider_id: number;
  required?: boolean;
  room_id: number;
  service_id: number;
  specialty_key?: string;
  start_time: string;
};

export type JourneyActivityOut = {
  activity_key: string;
  activity_kind: string;
  actual_end: string | null;
  actual_start: string | null;
  appointment_id: number | null;
  billing_status: string;
  clinic_id: number | null;
  consumables_status: string;
  created_at: string;
  depends_on_activity_id: number | null;
  form_resolution_status: string;
  id: number;
  journey_id: number;
  not_performed_reason: string | null;
  planned_end: string;
  planned_start: string;
  primary_provider_id: number | null;
  required: boolean;
  room_id: number | null;
  sequence: number;
  service_id: number;
  specialty_key: string;
  status: string;
  updated_at: string;
};

export type JourneyActivityStatusUpdate = {
  reason?: string | null;
  target_status: string;
};

export type JourneyAppointmentBrief = {
  date: string;
  end_time: string;
  episode_id: number | null;
  id: number;
  provider: JourneyProviderBrief;
  provider_id: number;
  room: JourneyRoomBrief;
  room_id: number;
  service: JourneyServiceBrief;
  service_id: number;
  source: string;
  start_time: string;
  status: string;
};

export type JourneyBlockerOut = {
  blocker_key: string;
  category: string;
  created_at: string;
  details: string | null;
  id: number;
  is_clinical: boolean;
  resolution_note: string | null;
  resolved_at: string | null;
  status: string;
  title: string;
};

export type JourneyCreate = {
  appointment_id: number;
  initial_stage?: string;
  intake_channel: string;
};

export type JourneyEventOut = {
  actor_type: string;
  actor_user_id: number | null;
  created_at: string;
  event_type: string;
  from_stage: string | null;
  id: number;
  metadata_json: {
} | null;
  request_id: string | null;
  source_channel: string;
  summary: string;
  to_stage: string | null;
};

export type JourneyOut = {
  activities?: Array<JourneyActivityOut>;
  appointment: JourneyAppointmentBrief;
  appointment_id: number;
  billing_status: string;
  blockers?: Array<JourneyBlockerOut>;
  check_in_status: string;
  closed_at: string | null;
  consumables_status: string;
  created_at: string;
  current_stage: string;
  document_status: string;
  encounter_status: string;
  events?: Array<JourneyEventOut>;
  id: number;
  intake_channel: string;
  patient: app__schemas__patient_journeys__PatientBrief;
  patient_id: number;
  payment_status: string;
  preparation_status: string;
  updated_at: string;
};

export type JourneyProviderBrief = {
  full_name: string;
  id: number;
};

export type JourneyRoomBrief = {
  id: number;
  name: string;
};

export type JourneyServiceBrief = {
  id: number;
  name: string;
};

export type JourneyStatusUpdate = {
  billing_status?: string | null;
  check_in_status?: string | null;
  consumables_status?: string | null;
  document_status?: string | null;
  encounter_status?: string | null;
  payment_status?: string | null;
  preparation_status?: string | null;
};

export type JourneySummaryOut = {
  content_json: {
};
  facts: Array<SummaryFactOut>;
  generated_at: string;
  id: number;
  journey_id: number;
  limitations_json: Array<unknown>;
  model_name: string;
  provider: string;
  reviewed_at: string | null;
  reviewed_by: number | null;
  source_refs_json: Array<unknown>;
  status: string;
};

export type JourneyTransition = {
  reason?: string | null;
  target_stage: string;
};

export type KnowledgeProtocolCreate = {
  key: string;
  rules?: Array<KnowledgeRuleCreate>;
  source_title: string;
  source_url: string;
  specialty: string;
  summary: string;
  title: string;
  version: string;
};

export type KnowledgeProtocolOut = {
  created_at: string;
  id: number;
  key: string;
  reviewed_at?: string | null;
  reviewed_by?: number | null;
  rules?: Array<KnowledgeRuleOut>;
  source_title: string;
  source_url: string;
  specialty: string;
  status: string;
  summary: string;
  title: string;
  updated_at: string;
  version: string;
};

export type KnowledgeRuleCreate = {
  condition_text: string;
  evidence_level?: string | null;
  guidance_text: string;
  label: string;
};

export type KnowledgeRuleOut = {
  condition_text: string;
  evidence_level?: string | null;
  guidance_text: string;
  id: number;
  label: string;
  position: number;
  protocol_id: number;
};

export type LabCancel = {
  reason: string;
};

export type LabCollection = {
  specimen_type: string;
};

export type LabHistoryItem = {
  flag: string;
  order_id: number;
  ordered_at: string;
  test_name: string;
  text_value: string | null;
  unit: string | null;
  value: string | null;
};

export type LabOrderCreate = {
  appointment_id?: number | null;
  episode_id?: number | null;
  external_laboratory?: string | null;
  notes?: string | null;
  ordered_at: string;
  patient_id: number;
  template_id?: number | null;
  tests?: Array<LabTestCreate>;
};

export type LabOrderOut = {
  appointment_id: number | null;
  cancellation_reason: string | null;
  cancelled_at: string | null;
  cancelled_by: number | null;
  collected_at: string | null;
  collected_by: number | null;
  created_at: string;
  dispatched_at: string | null;
  dispatched_by: number | null;
  episode_id: number | null;
  external_laboratory: string | null;
  external_received_at: string | null;
  id: number;
  notes: string | null;
  ordered_at: string;
  patient: app__schemas__laboratory__PatientBrief;
  patient_id: number;
  results: Array<LabResultOut>;
  review_conclusion: string | null;
  reviewed_at: string | null;
  reviewed_by: number | null;
  specimen_type: string;
  status: string;
  template_id: number | null;
};

export type LabResultOut = {
  flag: string;
  id: number;
  reference_high: string | null;
  reference_low: string | null;
  resulted_at: string | null;
  test_name: string;
  text_value: string | null;
  unit: string | null;
  value: string | null;
};

export type LabResultUpdate = {
  id: number;
  reference_high?: number | string | null;
  reference_low?: number | string | null;
  text_value?: string | null;
  unit?: string | null;
  value?: number | string | null;
};

export type LabResultsUpdate = {
  collected?: boolean;
  results: Array<LabResultUpdate>;
};

export type LabReview = {
  conclusion: string;
};

export type LabTemplateOut = {
  active: boolean;
  category: string;
  condition: string;
  description: string | null;
  id: number;
  name: string;
  tests: Array<{
}>;
};

export type LabTestCreate = {
  reference_high?: number | string | null;
  reference_low?: number | string | null;
  test_name: string;
  unit?: string | null;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type PackageActivityAssignment = {
  date: string;
  end_time: string;
  package_item_id: number;
  provider_id: number;
  room_id: number;
  start_time: string;
};

export type PackageBookRequest = {
  assignments: Array<PackageActivityAssignment>;
  episode_id?: number | null;
  idempotency_key: string;
  patient_id: number;
};

export type PackageCreate = {
  description?: string | null;
  name: string;
  package_key: string;
  specialty_key: string;
};

export type PackageItemCreate = {
  activity_key: string;
  activity_kind: string;
  billing_inclusion_rule?: string;
  default_duration_minutes: number;
  form_binding_override_version_id?: number | null;
  preferred_clinic_id?: number | null;
  preferred_room_type?: string | null;
  preparation_requirements_json?: Array<PreparationRequirementCreate>;
  relative_start_offset_minutes?: number;
  required?: boolean;
  sequence: number;
  service_id: number;
  specialty_key: string;
};

export type PackageMaterializeRequest = {
  assignments: Array<PackageActivityAssignment>;
};

export type PackageSchedulePreviewRequest = {
  assignments: Array<PackageActivityAssignment>;
  patient_id: number;
};

export type PackageVersionCreate = {
  items: Array<PackageItemCreate>;
};

export type PathologyCaseCreate = {
  external_lab?: string | null;
  idempotency_key?: string | null;
  specimens: Array<SpecimenCreate>;
};

export type PathologyCaseOut = {
  closed_at: string | null;
  collected_at: string | null;
  communication_attempts: number;
  communication_decided_at: string | null;
  communication_decided_by: number | null;
  communication_disposition: string | null;
  communication_note: string | null;
  external_case_number: string | null;
  external_lab: string | null;
  id: number;
  journey_id: number;
  lab_received_at: string | null;
  patient_id: number;
  patient_notified_at: string | null;
  result_received_at: string | null;
  reviewed_at: string | null;
  reviewed_by: number | null;
  sent_at: string | null;
  source_activity_id: number;
  specimens: Array<SpecimenOut>;
  status: string;
};

export type PathologyCommunicationDecision = {
  contact_attempts?: number;
  disposition: string;
  note?: string | null;
};

export type PathologyStatusUpdate = {
  external_case_number?: string | null;
  reason?: string | null;
  target_status: string;
};

export type PatientAppointmentAvailabilityOut = {
  appointment_id: number;
  clinic: AppointmentClinicSummary;
  date: string;
  end_time: string;
  patient_id: number;
  provider_name?: string | null;
  service_name?: string | null;
  start_time: string;
  status: string;
};

export type PatientClinicalRecordItem = {
  addendum_count?: number;
  author?: string | null;
  author_professional_role?: string | null;
  can_add_addendum?: boolean;
  can_edit?: boolean;
  clinic_id?: number | null;
  clinic_name?: string | null;
  created_at: string;
  date?: string | null;
  document_id: number;
  document_type: string;
  patient_id: number;
  signed_at?: string | null;
  specialty?: string | null;
  status: string;
  title: string;
};

export type PatientClinicalRecordResponse = {
  count: number;
  institution_id?: number | null;
  items: Array<PatientClinicalRecordItem>;
  patient_id: number;
};

export type PatientClinicalSummary = {
  awaiting_review_count: number;
  completed_procedures: Array<PatientKnowledgeItem>;
  current_therapy: Array<PatientKnowledgeItem>;
  draft_summary?: PatientClinicalSummaryRecordOut | null;
  draft_summary_is_stale?: boolean;
  generated_from_reviewed_documents: number;
  imaging: Array<PatientKnowledgeItem>;
  known_problems: Array<PatientKnowledgeItem>;
  laboratory: Array<PatientKnowledgeItem>;
  latest_recommendations: Array<PatientKnowledgeItem>;
  latest_reviewed_document_updated_at?: string | null;
  open_questions: Array<PatientKnowledgeItem>;
  pathology: Array<PatientKnowledgeItem>;
  patient_id: number;
  reviewed_summary?: PatientClinicalSummaryRecordOut | null;
  reviewed_summary_is_stale?: boolean;
  reviewed_summary_updated_at?: string | null;
  summary_warning?: string | null;
};

export type PatientClinicalSummaryRecordOut = {
  created_at: string;
  generated_by?: string | null;
  id: number;
  key_findings?: Array<string> | null;
  known_conditions?: Array<string> | null;
  last_recommendations?: Array<string> | null;
  open_items?: Array<string> | null;
  patient_id: number;
  reviewed_at?: string | null;
  reviewed_by?: number | null;
  risks?: Array<string> | null;
  source_document_ids?: Array<number> | null;
  status: string;
  summary_text?: string | null;
  updated_at: string;
};

export type PatientClinicalSummaryRecordUpdate = {
  key_findings?: Array<string> | null;
  known_conditions?: Array<string> | null;
  last_recommendations?: Array<string> | null;
  open_items?: Array<string> | null;
  risks?: Array<string> | null;
  source_document_ids?: Array<number> | null;
  status?: string | null;
  summary_text?: string | null;
};

export type PatientCreate = {
  date_of_birth?: string | null;
  email?: string | null;
  first_name: string;
  last_name: string;
  notes?: string | null;
  oib?: string | null;
  phone?: string | null;
};

export type PatientIdentityOut = {
  created_at: string;
  date_of_birth?: string | null;
  email?: string | null;
  first_name: string;
  id: number;
  last_name: string;
  oib?: string | null;
  phone?: string | null;
  updated_at: string;
};

export type PatientKnowledgeItem = {
  display_kind?: string | null;
  requires_attention?: boolean;
  severity?: string | null;
  sources: Array<PatientKnowledgeSource>;
  text: string;
};

export type PatientKnowledgeSource = {
  document_date?: string | null;
  document_id: number;
  document_type: string;
  origin?: string | null;
  source_type: string;
  title: string;
};

export type PatientOut = {
  created_at: string;
  date_of_birth?: string | null;
  email?: string | null;
  first_name: string;
  id: number;
  last_name: string;
  notes?: string | null;
  oib?: string | null;
  phone?: string | null;
  updated_at: string;
};

export type PatientUpdate = {
  date_of_birth?: string | null;
  email?: string | null;
  expected_updated_at?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  notes?: string | null;
  oib?: string | null;
  phone?: string | null;
};

export type PaymentRecord = {
  amount: number | string;
  method: string;
  reference?: string | null;
};

export type PaymentTransactionCreate = {
  amount: number | string;
  method: string;
  paid_at?: string | null;
  reference?: string | null;
};

export type PaymentTransactionOut = {
  amount: string;
  created_by?: number | null;
  id: number;
  invoice_id: number;
  method: string;
  paid_at?: string | null;
  reference?: string | null;
};

export type PreparationAssign = {
  channel?: string;
  template_id: number;
};

export type PreparationOut = {
  acknowledged_at: string | null;
  assigned_at: string;
  completed_at: string | null;
  id: number;
  journey_id: number;
  requirement_states_json: {
};
  status: string;
  template: PreparationTemplateOut;
  template_id: number;
};

export type PreparationRequirementCreate = {
  category: string;
  label: string;
  patient_instruction: string;
  required?: boolean;
  requirement_key: string;
  source_template_key?: string;
  source_template_version?: string;
};

export type PreparationTemplateCreate = {
  approved?: boolean;
  name: string;
  patient_instructions: string;
  procedure_type: string;
  reminder_schedule_json?: Array<{
}>;
  requirements_json?: Array<{
}>;
  template_key: string;
  version: string;
};

export type PreparationTemplateOut = {
  active: boolean;
  approved_at: string | null;
  id: number;
  name: string;
  patient_instructions: string;
  procedure_type: string;
  reminder_schedule_json: Array<unknown>;
  requirements_json: Array<unknown>;
  template_key: string;
  version: string;
};

export type ProviderCreate = {
  clinic_id: number;
  email: string;
  full_name: string;
  specialty?: string | null;
  staff_role?: string;
  weekly_working_hours?: {
  [key: string]: {
};
} | null;
  work_end: string;
  work_start: string;
};

export type ProviderOut = {
  active: boolean;
  available_for_work?: boolean;
  clinic?: ClinicOut | null;
  clinic_id?: number | null;
  created_at: string;
  email?: string | null;
  full_name: string;
  id: number;
  specialty?: string | null;
  staff_role?: string;
  updated_at: string;
  weekly_working_hours?: {
  [key: string]: {
};
};
  work_end: string;
  work_start: string;
};

export type ProviderScheduleUpdate = {
  weekly_working_hours: {
  [key: string]: {
};
};
};

export type PurchaseOrderCreate = {
  expected_delivery_date?: string | null;
  notes?: string | null;
  order_date?: string | null;
  status?: string;
  supplier_id: number;
  total_amount?: number | string;
};

export type PurchaseOrderLineCreate = {
  inventory_item_id: number;
  quantity_ordered: number | string;
  unit_price?: number | string;
  vat_rate?: number | string;
};

export type PurchaseOrderLineOut = {
  id: number;
  inventory_item_id: number;
  purchase_order_id: number;
  quantity_ordered: string;
  quantity_received: string;
  unit_price?: string;
  vat_rate?: string;
};

export type PurchaseOrderLineUpdate = {
  inventory_item_id?: number | null;
  quantity_ordered?: number | string | null;
  unit_price?: number | string | null;
  vat_rate?: number | string | null;
};

export type PurchaseOrderOut = {
  created_at: string;
  expected_delivery_date?: string | null;
  id: number;
  lines?: Array<PurchaseOrderLineOut>;
  notes?: string | null;
  order_date?: string | null;
  status?: string;
  supplier_id: number;
  total_amount?: string;
  updated_at: string;
};

export type PurchaseOrderReceiveLine = {
  expiration_date?: string | null;
  location_id: number;
  lot_number?: string | null;
  purchase_order_line_id: number;
  purchase_price?: number | string | null;
  quantity_received: number | string;
};

export type PurchaseOrderReceiveRequest = {
  lines: Array<PurchaseOrderReceiveLine>;
};

export type ReadinessCheck = {
  action?: string | null;
  count?: number | null;
  decision_impact?: string;
  key: string;
  label: string;
  message: string;
  severity_reason?: string | null;
  status: string;
  target_label?: string | null;
  target_path?: string | null;
};

export type ReadinessOut = {
  checks: Array<ReadinessCheck>;
  demo_mode: boolean;
  fiscalization_mode: string;
  real_data_allowed: boolean;
  status: string;
  summary: {
  [key: string]: number;
};
};

export type ReceptionArrivalRequest = {
  identity_verified?: boolean;
  patient?: ReceptionPatientUpdate | null;
};

export type ReceptionCheckInComplete = {
  idempotency_key?: string | null;
  items?: Array<ReceptionCheckInItemResult>;
  reception_note?: string | null;
};

export type ReceptionCheckInItemResult = {
  activity_ids?: Array<number>;
  details?: {
};
  item_key: string;
  note?: string | null;
};

export type ReceptionPatientUpdate = {
  date_of_birth?: string | null;
  email?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  oib?: string | null;
  phone?: string | null;
};

export type ReceptionSlot = {
  appointment?: AppointmentOut | null;
  empty?: boolean;
  span?: number;
  time: string;
};

export type ReminderOut = {
  channel: string;
  communication_event_id: number | null;
  id: number;
  journey_id: number;
  reminder_type: string;
  scheduled_at: string;
  status: string;
};

export type ReportDeliveryOut = {
  alternate_recipient_reason: string | null;
  approved_by: number;
  channel: string;
  correlation_id: string;
  delivered_at: string | null;
  failure_reason: string | null;
  id: number;
  initiated_by: number;
  provider_mode: string;
  queued_at: string;
  recipient: string;
  recipient_source: string;
  report_id: number;
  sent_at: string | null;
  status: string;
};

export type ReportDeliveryRequest = {
  acknowledge_superseded?: boolean;
  alternate_recipient_reason?: string | null;
  channel?: string;
  idempotency_key?: string | null;
  recipient: string;
  recipient_source?: string;
  report_ids: Array<number>;
};

export type ReportLinkCreate = {
  clinical_document_id: number;
};

export type ReportPrintOut = {
  id: number;
  printed_at: string;
  printed_by: number;
  report_id: number;
  request_id: string | null;
};

export type RequirementUpdate = {
  requirement_key: string;
  state: string;
};

export type RoomCreate = {
  clinic_id: number;
  name: string;
  type?: string | null;
};

export type RoomOut = {
  active: boolean;
  clinic?: ClinicOut | null;
  clinic_id?: number | null;
  created_at: string;
  id: number;
  name: string;
  type?: string | null;
  updated_at: string;
  visible_in_catalog?: boolean;
};

export type SensitiveAccessEventIn = {
  action: 'patient.viewed' | 'clinical_workspace.opened' | 'clinical_form.viewed' | 'signed_report.viewed' | 'source_document.viewed' | 'source_document.downloaded' | 'billing_details.viewed' | 'patient_export.created' | 'clinical_report.printed' | 'audit_log.viewed';
  entity_id?: number | null;
  entity_type: 'Patient' | 'PatientJourney' | 'ClinicalFormInstance' | 'SignedClinicalReport' | 'ClinicalDocument' | 'Invoice' | 'PatientExport' | 'AuditLog';
  interaction_id?: string | null;
  surface: 'patient_workspace' | 'clinical_workspace' | 'daily_dashboard' | 'document_center' | 'report_viewer' | 'billing_panel' | 'audit_viewer';
};

export type SensitiveAccessEventOut = {
  action: string;
  entity_id: number | null;
  entity_type: string;
  id: number;
};

export type ServiceCreate = {
  active?: boolean;
  code?: string | null;
  duration_minutes?: number;
  module_id?: number | null;
  name: string;
  price?: number | string;
  visible_in_catalog?: boolean;
};

export type ServiceMaterialCreate = {
  default_quantity?: number | string;
  inventory_item_id: number;
  notes?: string | null;
  required?: boolean;
  variable_quantity_allowed?: boolean;
};

export type ServiceOut = {
  active?: boolean;
  clinic_ids?: Array<number>;
  code?: string | null;
  duration_minutes?: number;
  id: number;
  module_id?: number | null;
  name: string;
  price?: string;
  room_ids?: Array<number>;
  visible_in_catalog?: boolean;
};

export type ServiceUpdate = {
  duration_minutes?: number | null;
  price?: number | string | null;
  room_ids?: Array<number> | null;
};

export type SignedReportOut = {
  activity_id: number;
  clinical_document_id: number;
  content_hash: string;
  document_type: string;
  form_instance_id: number;
  form_version_id: number;
  hash_algorithm: string;
  id: number;
  journey_id: number;
  patient_id: number;
  rendered_content: string;
  signed_at: string;
  signer_name: string;
  signer_user_id: number;
  structured_data_json: {
};
  superseded_at: string | null;
  supersedes_report_id: number | null;
  title: string;
  version_number: number;
};

export type SpecimenCreate = {
  anatomical_site: string;
  collection_time: string;
  container?: string | null;
  fixation?: string | null;
  notes?: string | null;
  source_intervention_id: number;
  specimen_label: string;
  specimen_type: string;
};

export type SpecimenOut = {
  anatomical_site: string;
  case_id: number;
  collection_time: string;
  container?: string | null;
  fixation?: string | null;
  id: number;
  notes?: string | null;
  source_intervention_id: number;
  specimen_label: string;
  specimen_type: string;
};

export type StockMovementCreate = {
  batch_id?: number | null;
  from_location_id?: number | null;
  inventory_item_id: number;
  movement_type: string;
  quantity: number | string;
  reason?: string | null;
  related_appointment_id?: number | null;
  related_invoice_id?: number | null;
  to_location_id?: number | null;
};

export type StockMovementOut = {
  batch_id?: number | null;
  created_at: string;
  created_by?: number | null;
  from_location_id?: number | null;
  id: number;
  inventory_item_id: number;
  movement_type: string;
  quantity: string;
  reason?: string | null;
  related_appointment_id?: number | null;
  related_invoice_id?: number | null;
  to_location_id?: number | null;
};

export type SummaryFactOut = {
  confidence: string | null;
  fact_type: string;
  id: number;
  limitation: string | null;
  review_status: string;
  reviewed_at: string | null;
  reviewed_by: number | null;
  source_document_id: number | null;
  statement: string;
};

export type SummaryFactReview = {
  action: string;
};

export type SupplierCreate = {
  address?: string | null;
  contact_person?: string | null;
  email?: string | null;
  name: string;
  notes?: string | null;
  phone?: string | null;
  vat_id?: string | null;
};

export type SupplierOut = {
  address?: string | null;
  contact_person?: string | null;
  created_at: string;
  email?: string | null;
  id: number;
  name: string;
  notes?: string | null;
  phone?: string | null;
  updated_at: string;
  vat_id?: string | null;
};

export type TherapyComplete = {
  note?: string | null;
};

export type TherapyCreate = {
  end_date?: string | null;
  episode_id?: number | null;
  instructions: string;
  name: string;
  notes?: string | null;
  patient_id: number;
  prescriber?: string | null;
  start_date: string;
};

export type TherapyOut = {
  completed_at: string | null;
  completion_note: string | null;
  created_at: string;
  end_date: string | null;
  episode_id: number | null;
  id: number;
  instructions: string;
  name: string;
  notes: string | null;
  parent_therapy_id: number | null;
  patient: app__schemas__therapies__PatientBrief;
  patient_id: number;
  prescriber: string | null;
  start_date: string;
  status: string;
  stop_reason: string | null;
  stopped_at: string | null;
};

export type TherapyRenew = {
  end_date?: string | null;
  instructions?: string | null;
  start_date: string;
};

export type TherapyStop = {
  reason: string;
};

export type TherapyUpdate = {
  end_date?: string | null;
  episode_id?: number | null;
  instructions: string;
  name: string;
  notes?: string | null;
  prescriber?: string | null;
  start_date: string;
};

export type TimelineItem = {
  date: string;
  event_type: string;
  journey_id: number;
  provenance?: {
};
  review_state?: string | null;
  source_url?: string | null;
  summary?: string | null;
  title: string;
};

export type TokenResponse = {
  access_token: string;
  token_type?: string;
  user: {
};
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type VisitDocumentOut = {
  latest_delivery: ReportDeliveryOut | null;
  print_count: number;
  report: SignedReportOut;
};

export type WorkflowChecklistItemOut = {
  completed: boolean;
  completed_at?: string | null;
  completed_by?: number | null;
  id: number;
  label: string;
  position: number;
  task_id: number;
};

export type WorkflowTaskCreate = {
  appointment_id?: number | null;
  assignee_provider_id?: number | null;
  checklist_items?: Array<string>;
  description?: string | null;
  due_date?: string | null;
  episode_id?: number | null;
  patient_id: number;
  priority?: string;
  responsible_role?: string | null;
  template_id?: number | null;
  title: string;
};

export type WorkflowTaskOut = {
  appointment_id?: number | null;
  assignee_provider_id?: number | null;
  checklist?: Array<WorkflowChecklistItemOut>;
  completed_at?: string | null;
  created_at: string;
  created_by?: number | null;
  description?: string | null;
  due_date?: string | null;
  episode?: ClinicalEpisodeOut | null;
  episode_id?: number | null;
  id: number;
  patient?: PatientOut | null;
  patient_id: number;
  priority: string;
  provider?: ProviderOut | null;
  responsible_role?: string | null;
  status: string;
  template_id?: number | null;
  title: string;
  updated_at: string;
};

export type WorkflowTaskUpdate = {
  assignee_provider_id?: number | null;
  description?: string | null;
  due_date?: string | null;
  priority?: string | null;
  responsible_role?: string | null;
  status?: string | null;
  title?: string | null;
};

export type WorkflowTemplateCreate = {
  active?: boolean;
  checklist_items?: Array<string>;
  default_priority?: string;
  description?: string | null;
  key: string;
  name: string;
};

export type WorkflowTemplateOut = {
  active?: boolean;
  checklist_items?: Array<string>;
  created_at: string;
  default_priority?: string;
  description?: string | null;
  id: number;
  key: string;
  name: string;
  updated_at: string;
};

export type app__schemas__laboratory__PatientBrief = {
  date_of_birth?: string | null;
  first_name: string;
  id: number;
  last_name: string;
};

export type app__schemas__patient_journeys__PatientBrief = {
  date_of_birth?: string | null;
  email?: string | null;
  email_verified_at?: string | null;
  first_name: string;
  id: number;
  last_name: string;
  notes?: string | null;
  oib?: string | null;
  phone?: string | null;
};

export type app__schemas__therapies__PatientBrief = {
  date_of_birth?: string | null;
  first_name: string;
  id: number;
  last_name: string;
};
