import { useState } from "react";
import { api } from "../../api/client";
import type { PathologyCase } from "../../types/program2";

const labels: Record<string, string> = { specimens_ready: "Uzorci spremni", sent_to_lab: "Predano laboratoriju", received_by_lab: "Laboratorij zaprimio", awaiting_result: "Čeka nalaz", clinician_review_required: "Čeka pregled liječnika", clinician_reviewed: "Liječnik pregledao", patient_notification_ready: "Čeka komunikacijsku odluku", patient_notified: "Pacijent obaviješten", closed: "Zatvoreno", cancelled: "Otkazano" };
const communicationLabels: Record<string, string> = { delivered_approved_report: "Dostavljen odobreni nalaz", direct_contact: "Izravan kontakt", reviewed_at_follow_up_visit: "Objašnjeno na kontroli", no_notification_required: "Obavijest nije potrebna", patient_declined: "Pacijent odbio obavijest", unable_to_contact: "Kontakt nije uspio", transferred_to_external_care: "Predano vanjskoj skrbi", cancelled_as_duplicate: "Duplikat slučaja" };
const next: Record<string, { target: string; label: string } | undefined> = { sent_to_lab: { target: "received_by_lab", label: "Laboratorij zaprimio" }, received_by_lab: { target: "awaiting_result", label: "Čeka nalaz" }, clinician_reviewed: { target: "patient_notification_ready", label: "Pripremi komunikaciju" } };

export function PathologyFollowUpPanel({ items, onChanged }: { items: PathologyCase[]; onChanged: () => Promise<void> }) {
  const [transport, setTransport] = useState<PathologyCase | null>(null); const [caseNumber, setCaseNumber] = useState(""); const [decision, setDecision] = useState<PathologyCase | null>(null); const [disposition, setDisposition] = useState("direct_contact"); const [note, setNote] = useState(""); const [attempts, setAttempts] = useState(0);
  async function transition(item: PathologyCase, target: string, external?: string) { await api(`/api/pathology-cases/${item.id}/transition`, { method: "POST", body: JSON.stringify({ target_status: target, external_case_number: external || null }) }); await onChanged(); }
  async function saveDecision() { if (!decision) return; await api(`/api/pathology-cases/${decision.id}/communication-decision`, { method: "POST", body: JSON.stringify({ disposition, note: note || null, contact_attempts: attempts }) }); setDecision(null); await onChanged(); }
  if (!items.length) return null;
  return <section className="journey-panel pathology-follow-up"><header><div><span className="eyebrow">Praćenje nakon dolaska</span><h2>Patologija</h2></div></header>{items.map(item => <article key={item.id}><i className={`activity-dot ${item.status === "clinician_review_required" ? "in_progress" : item.status === "closed" ? "completed" : ""}`}/><div><b>{labels[item.status] ?? "Nepoznato stanje"}</b><small>{item.specimens.map(specimen => `${specimen.specimen_label}: ${specimen.anatomical_site}`).join(" · ")}</small><small>{item.communication_disposition ? `Komunikacija: ${communicationLabels[item.communication_disposition] ?? "evidentirana"}` : "Komunikacijska odluka nije evidentirana"}</small></div>{item.status === "specimens_ready" && <button type="button" onClick={() => { setTransport(item); setCaseNumber(item.external_case_number ?? ""); }}>Predaj laboratoriju</button>}{next[item.status] && <button type="button" onClick={() => transition(item, next[item.status]!.target)}>{next[item.status]!.label}</button>}{["clinician_reviewed", "patient_notification_ready", "patient_notified"].includes(item.status) && !item.communication_disposition && <button type="button" onClick={() => setDecision(item)}>Komunikacijska odluka</button>}{item.communication_disposition && item.status !== "closed" && <button type="button" onClick={() => transition(item, "closed")}>Zatvori slučaj</button>}</article>)}
    {transport && <div className="modal-backdrop"><section className="modal-panel" role="dialog" aria-modal="true"><header><h2>Predaja laboratoriju</h2></header><label>Vanjski broj slučaja (opcionalno)<input value={caseNumber} onChange={event => setCaseNumber(event.target.value)}/></label><footer><button onClick={() => setTransport(null)}>Odustani</button><button className="primary" onClick={async () => { await transition(transport, "sent_to_lab", caseNumber); setTransport(null); }}>Potvrdi</button></footer></section></div>}
    {decision && <div className="modal-backdrop"><section className="modal-panel" role="dialog" aria-modal="true"><header><h2>Komunikacijska odluka</h2></header><label>Način<select value={disposition} onChange={event => setDisposition(event.target.value)}><option value="direct_contact">Izravan kontakt</option><option value="reviewed_at_follow_up_visit">Pregledano na kontroli</option><option value="no_notification_required">Obavijest nije potrebna</option><option value="patient_declined">Pacijent odbio</option><option value="unable_to_contact">Nije moguće kontaktirati</option><option value="transferred_to_external_care">Predano vanjskoj skrbi</option></select></label><label>Bilješka<textarea value={note} onChange={event => setNote(event.target.value)}/></label>{disposition === "unable_to_contact" && <label>Broj pokušaja<input type="number" min="3" value={attempts} onChange={event => setAttempts(Number(event.target.value))}/></label>}<footer><button onClick={() => setDecision(null)}>Odustani</button><button className="primary" disabled={!note.trim() || (disposition === "unable_to_contact" && attempts < 3)} onClick={saveDecision}>Spremi odluku</button></footer></section></div>}
  </section>;
}
