import { ExternalLink, ShieldAlert } from "lucide-react";
import { useState, type ReactNode } from "react";
import { journeyStatusLabel } from "./journeyStatus";
export function Panel({title,children}:{title:string;children:ReactNode}){return <section className="journey-panel"><h2>{title}</h2>{children}</section>}
export function DocumentReadinessPanel({status}:{status:string}){return <Panel title="Dokumenti"><p>Status: <strong>{journeyStatusLabel(status)}</strong></p></Panel>}
export function PreparationPanel({status}:{status:string}){return <Panel title="Priprema"><p>Status: <strong>{journeyStatusLabel(status)}</strong></p></Panel>}
export function CheckInChecklist({data}:{data:any}){return <Panel title="Prijemna provjera">{data?.items?.map((item:any)=><p className="journey-check" key={item.id}><span>{item.label}</span><strong>{journeyStatusLabel(item.state)}</strong></p>)??<p>Provjera nije započeta.</p>}</Panel>}
export function PatientTimeline({items}:{items:any[]}){return <Panel title="Timeline">{items.map(item=><article className="journey-timeline-item" key={`${item.event_type}-${item.date}-${item.title}`}><small>{new Date(item.date).toLocaleString("hr-HR")}</small><strong>{item.title}</strong>{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer">Otvori izvor <ExternalLink size={13}/></a>}</article>)}</Panel>}
export function SourceDocumentViewer({documents}:{documents:any[]}){return <Panel title="Izvorni dokumenti">{documents.map(item=><a className="journey-source" key={item.id} href={`/api/clinical-documents/${item.id}/source`} target="_blank" rel="noreferrer"><span><strong>{item.title}</strong><small>{journeyStatusLabel(item.review_status)}</small></span><ExternalLink size={15}/></a>)}{!documents.length&&<p>Nema povezanih dokumenata.</p>}</Panel>}
export function AISummaryPanel({summary}:{summary:any}){return <Panel title="AI prijedlog — pregled obavezan">{summary?.limitations_json?.map((item:string)=><small className="journey-limitation" key={item}>{item}</small>)}{summary?.facts?.map((fact:any)=><article className="journey-ai-fact" key={fact.id}><strong>{fact.statement}</strong><small>{fact.fact_type} · {journeyStatusLabel(fact.review_status)}</small>{fact.source_document_id&&<a href={`/api/clinical-documents/${fact.source_document_id}/source`} target="_blank" rel="noreferrer">Izvor #{fact.source_document_id}</a>}</article>)}{!summary&&<p>Sažetak nije generiran.</p>}</Panel>}
export function EncounterPanel({draft,setDraft,status,onOpen,onSave,onComplete}:{draft:any;setDraft:(v:any)=>void;status?:string;onOpen:()=>void;onSave:()=>void;onComplete:()=>void}){const fields=[['anamnesis','Anamneza'],['examination','Pregled'],['procedure_findings','Nalaz postupka'],['diagnosis','Dijagnoza liječnika'],['treatment','Terapija'],['recommendations','Preporuke'],['follow_up_plan','Plan kontrole']];return <Panel title="Trenutačni klinički susret"><div className="encounter-status">Status: <strong>{status?journeyStatusLabel(status):'nije otvoren'}</strong></div>{status?fields.map(([key,label])=><label className="encounter-field" key={key}>{label}<textarea disabled={status==='completed'} value={draft[key]??''} onChange={event=>setDraft({...draft,[key]:event.target.value})}/></label>):<button className="primary" onClick={onOpen}>Otvori susret</button>} {status==='in_progress'&&<div className="form-actions"><button onClick={onSave}>Spremi bilješku</button><button className="primary" onClick={onComplete}>Dovrši postupak</button></div>}</Panel>}
export function ConsumablesPanel({status,onConfirmNone}:{status:string;onConfirmNone?:()=>void}){return <Panel title="Potrošni materijal"><p>Status: <strong>{journeyStatusLabel(status)}</strong></p>{status==='not_ready'&&onConfirmNone&&<button onClick={onConfirmNone}>Nema potrošnog materijala</button>}</Panel>}
export function BillingPanel({status,invoice,onPrepare}:{status:string;invoice?:any;onPrepare?:()=>void}){return <Panel title="Račun"><p>Status: <strong>{journeyStatusLabel(status)}</strong></p>{invoice&&<p>{invoice.number}<br/><strong>{invoice.total} EUR</strong></p>}{status==='ready'&&onPrepare&&<button className="primary" onClick={onPrepare}>Izradi i izdaj račun</button>}</Panel>}
export function PaymentPanel({status,invoice,onPay,onDefer,onClose}:{status:string;invoice?:any;onPay?:(amount:string,method:string)=>void;onDefer?:()=>void;onClose?:()=>void}){const[amount,setAmount]=useState(invoice?.total??'');const[method,setMethod]=useState('card');return <Panel title="Plaćanje"><p>Status: <strong>{journeyStatusLabel(status)}</strong></p>{status==='unpaid'&&<><label>Iznos<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Način<select value={method} onChange={e=>setMethod(e.target.value)}><option value="card">Kartica</option><option value="cash">Gotovina</option><option value="bank_transfer">Bankovna uplata</option><option value="insurance">Osiguranje</option></select></label><button className="primary" onClick={()=>onPay?.(amount,method)}>Evidentiraj uplatu</button><button onClick={onDefer}>Odgođeno plaćanje</button></>}{['paid','deferred','refunded','cancelled'].includes(status)&&onClose&&<button className="primary" onClick={onClose}>Završi tijek pacijenta</button>}</Panel>}
export function BlockerPanel({items}:{items:any[]}){return <Panel title="Blokatori">{items.filter(item=>item.status==='open').map(item=><p className="journey-blocker" key={item.id}><ShieldAlert size={15}/><span><strong>{item.title}</strong><small>{item.details}</small></span></p>)}{!items.some(item=>item.status==='open')&&<p>Nema otvorenih blokatora.</p>}</Panel>}
