import { ExternalLink, ShieldAlert } from "lucide-react";
import type { ReactNode } from "react";
export function Panel({title,children}:{title:string;children:ReactNode}){return <section className="journey-panel"><h2>{title}</h2>{children}</section>}
export function DocumentReadinessPanel({status}:{status:string}){return <Panel title="Dokumenti"><p>Status: <strong>{status}</strong></p></Panel>}
export function PreparationPanel({status}:{status:string}){return <Panel title="Priprema"><p>Status: <strong>{status}</strong></p></Panel>}
export function CheckInChecklist({data}:{data:any}){return <Panel title="Check-in">{data?.items?.map((item:any)=><p className="journey-check" key={item.id}><span>{item.label}</span><strong>{item.state}</strong></p>)??<p>Provjera nije započeta.</p>}</Panel>}
export function PatientTimeline({items}:{items:any[]}){return <Panel title="Timeline">{items.map(item=><article className="journey-timeline-item" key={`${item.event_type}-${item.date}-${item.title}`}><small>{new Date(item.date).toLocaleString("hr-HR")}</small><strong>{item.title}</strong>{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer">Otvori izvor <ExternalLink size={13}/></a>}</article>)}</Panel>}
export function SourceDocumentViewer({documents}:{documents:any[]}){return <Panel title="Izvorni dokumenti">{documents.map(item=><a className="journey-source" key={item.id} href={`/api/clinical-documents/${item.id}/source`} target="_blank" rel="noreferrer"><span><strong>{item.title}</strong><small>{item.review_status}</small></span><ExternalLink size={15}/></a>)}{!documents.length&&<p>Nema povezanih dokumenata.</p>}</Panel>}
export function AISummaryPanel({summary}:{summary:any}){return <Panel title="AI prijedlog — pregled obavezan">{summary?.limitations_json?.map((item:string)=><small className="journey-limitation" key={item}>{item}</small>)}{summary?.facts?.map((fact:any)=><article className="journey-ai-fact" key={fact.id}><strong>{fact.statement}</strong><small>{fact.fact_type} · {fact.review_status}</small>{fact.source_document_id&&<a href={`/api/clinical-documents/${fact.source_document_id}/source`} target="_blank" rel="noreferrer">Izvor #{fact.source_document_id}</a>}</article>)}{!summary&&<p>Sažetak nije generiran.</p>}</Panel>}
export function EncounterPanel({draft,setDraft,status,onOpen,onSave,onComplete}:{draft:any;setDraft:(v:any)=>void;status?:string;onOpen:()=>void;onSave:()=>void;onComplete:()=>void}){const fields=[['anamnesis','Anamneza'],['examination','Pregled'],['procedure_findings','Nalaz postupka'],['diagnosis','Dijagnoza liječnika'],['treatment','Terapija'],['recommendations','Preporuke'],['follow_up_plan','Plan kontrole']];return <Panel title="Trenutačni klinički susret"><div className="encounter-status">Status: <strong>{status??'nije otvoren'}</strong></div>{status?fields.map(([key,label])=><label className="encounter-field" key={key}>{label}<textarea disabled={status==='completed'} value={draft[key]??''} onChange={event=>setDraft({...draft,[key]:event.target.value})}/></label>):<button className="primary" onClick={onOpen}>Otvori susret</button>} {status==='in_progress'&&<div className="form-actions"><button onClick={onSave}>Spremi bilješku</button><button className="primary" onClick={onComplete}>Dovrši postupak</button></div>}</Panel>}
export function ConsumablesPanel({status}:{status:string}){return <Panel title="Potrošni materijal"><p>{status}</p></Panel>}
export function BillingPanel({status}:{status:string}){return <Panel title="Račun"><p>{status}</p></Panel>}
export function PaymentPanel({status}:{status:string}){return <Panel title="Plaćanje"><p>{status}</p></Panel>}
export function BlockerPanel({items}:{items:any[]}){return <Panel title="Blokatori">{items.filter(item=>item.status==='open').map(item=><p className="journey-blocker" key={item.id}><ShieldAlert size={15}/><span><strong>{item.title}</strong><small>{item.details}</small></span></p>)}{!items.some(item=>item.status==='open')&&<p>Nema otvorenih blokatora.</p>}</Panel>}
