"""Program 2 preparation, forms and communication.
Revision ID: 0040_program2_preparation
Revises: 0039_program2_journey
"""
from alembic import op
import sqlalchemy as sa
revision="0040_program2_preparation";down_revision="0039_program2_journey";branch_labels=None;depends_on=None
def timestamps(): return [sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now())]
def upgrade():
 op.create_table("preparation_plan_templates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("template_key",sa.String(100),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("procedure_type",sa.String(100),nullable=False),sa.Column("version",sa.String(40),nullable=False),sa.Column("patient_instructions",sa.Text(),nullable=False),sa.Column("requirements_json",sa.JSON(),nullable=False),sa.Column("reminder_schedule_json",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("approved_by",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("approved_at",sa.DateTime(timezone=True)),*timestamps(),sa.UniqueConstraint("template_key","version",name="uq_preparation_template_version"));op.create_index("ix_preparation_plan_templates_template_key","preparation_plan_templates",["template_key"]);op.create_index("ix_preparation_plan_templates_procedure_type","preparation_plan_templates",["procedure_type"]);op.create_index("ix_preparation_plan_templates_active","preparation_plan_templates",["active"])
 op.create_table("journey_preparations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("journey_id",sa.Integer(),sa.ForeignKey("patient_journeys.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("template_id",sa.Integer(),sa.ForeignKey("preparation_plan_templates.id"),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="assigned"),sa.Column("assigned_by",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("assigned_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("requirement_states_json",sa.JSON(),nullable=False),*timestamps());op.create_index("ix_journey_preparations_journey_id","journey_preparations",["journey_id"]);op.create_index("ix_journey_preparations_status","journey_preparations",["status"])
 op.create_table("patient_form_templates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("template_key",sa.String(100),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("version",sa.String(40),nullable=False),sa.Column("fields_json",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("approved_by",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("approved_at",sa.DateTime(timezone=True)),*timestamps(),sa.UniqueConstraint("template_key","version",name="uq_patient_form_template_version"));op.create_index("ix_patient_form_templates_template_key","patient_form_templates",["template_key"]);op.create_index("ix_patient_form_templates_active","patient_form_templates",["active"])
 op.create_table("journey_forms",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("journey_id",sa.Integer(),sa.ForeignKey("patient_journeys.id",ondelete="CASCADE"),nullable=False),sa.Column("template_id",sa.Integer(),sa.ForeignKey("patient_form_templates.id"),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="requested"),sa.Column("answers_json",sa.JSON()),sa.Column("requested_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("reviewed_by",sa.Integer(),sa.ForeignKey("users.id")),*timestamps());op.create_index("ix_journey_forms_journey_id","journey_forms",["journey_id"]);op.create_index("ix_journey_forms_status","journey_forms",["status"])
 op.create_table("document_requests",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("journey_id",sa.Integer(),sa.ForeignKey("patient_journeys.id",ondelete="CASCADE"),nullable=False),sa.Column("document_type",sa.String(100),nullable=False),sa.Column("title",sa.String(220),nullable=False),sa.Column("mandatory",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("status",sa.String(40),nullable=False,server_default="requested"),sa.Column("clinical_document_id",sa.Integer(),sa.ForeignKey("clinical_documents.id")),sa.Column("requested_by",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("resolved_at",sa.DateTime(timezone=True)),*timestamps());op.create_index("ix_document_requests_journey_id","document_requests",["journey_id"]);op.create_index("ix_document_requests_document_type","document_requests",["document_type"]);op.create_index("ix_document_requests_status","document_requests",["status"])
 op.create_table("communication_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("journey_id",sa.Integer(),sa.ForeignKey("patient_journeys.id",ondelete="CASCADE"),nullable=False),sa.Column("channel",sa.String(40),nullable=False),sa.Column("template_key",sa.String(120),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="queued"),sa.Column("scheduled_at",sa.DateTime(timezone=True)),sa.Column("sent_at",sa.DateTime(timezone=True)),sa.Column("delivered_at",sa.DateTime(timezone=True)),sa.Column("failure_reason",sa.Text()),sa.Column("correlation_id",sa.String(100),nullable=False,unique=True),*timestamps());op.create_index("ix_communication_events_journey_id","communication_events",["journey_id"]);op.create_index("ix_communication_events_channel","communication_events",["channel"]);op.create_index("ix_communication_events_status","communication_events",["status"]);op.create_index("ix_communication_events_scheduled_at","communication_events",["scheduled_at"]);op.create_index("ix_communication_events_correlation_id","communication_events",["correlation_id"],unique=True)
 op.create_table("journey_reminders",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("journey_id",sa.Integer(),sa.ForeignKey("patient_journeys.id",ondelete="CASCADE"),nullable=False),sa.Column("reminder_type",sa.String(100),nullable=False),sa.Column("channel",sa.String(40),nullable=False),sa.Column("scheduled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="scheduled"),sa.Column("communication_event_id",sa.Integer(),sa.ForeignKey("communication_events.id")),*timestamps());op.create_index("ix_journey_reminders_journey_id","journey_reminders",["journey_id"]);op.create_index("ix_journey_reminders_reminder_type","journey_reminders",["reminder_type"]);op.create_index("ix_journey_reminders_scheduled_at","journey_reminders",["scheduled_at"]);op.create_index("ix_journey_reminders_status","journey_reminders",["status"])
def downgrade():
 for table in ("journey_reminders","communication_events","document_requests","journey_forms","patient_form_templates","journey_preparations","preparation_plan_templates"): op.drop_table(table)
