import { FormEvent, useMemo, useState } from "react";
import { Building2, Clock3, DoorOpen, Eye, EyeOff, Mail, Search, Trash2, UserRoundCog } from "lucide-react";
import { api } from "../api/client";
import { HelpHint } from "../components/HelpHint";
import { useApi } from "../hooks/useApi";
import { Clinic, DaySchedule, Provider, Room } from "../types";

const DAYS=["Ponedjeljak","Utorak","Srijeda","Četvrtak","Petak","Subota","Nedjelja"];
const TIME_OPTIONS=Array.from({length:14},(_,index)=>`${String(7+index).padStart(2,"0")}:00`);
const defaultWeek=()=>Object.fromEntries(DAYS.map((_,day)=>[String(day),{enabled:day<5,start:"07:00",end:"15:00"}])) as Record<string,DaySchedule>;
const roleLabel=(role?:string)=>role==="nurse"?"Medicinska sestra/tehničar":role==="secretary"?"Tajnik/administrator":"Liječnik";
function WeekEditor({value,onChange,onSave,onCancel}:{value:Record<string,DaySchedule>;onChange:(value:Record<string,DaySchedule>)=>void;onSave:()=>void;onCancel:()=>void}){return <div className="weekly-hours schedule-edit-panel"><h3>Promijeni radno vrijeme</h3><p className="field-help">Radno vrijeme klinike: 07:00–20:00.</p>{DAYS.map((label,index)=>{const d=value[String(index)];return <div className={d.enabled?"":"day-off"} key={label}><label><input type="checkbox" checked={d.enabled} onChange={e=>onChange({...value,[String(index)]:{...d,enabled:e.target.checked}})}/>{label}</label><select aria-label={`${label}, početak rada`} disabled={!d.enabled} value={d.start} onChange={e=>{const start=e.target.value;const end=d.end<=start?TIME_OPTIONS.find(time=>time>start)??"20:00":d.end;onChange({...value,[String(index)]:{...d,start,end}})}}>{TIME_OPTIONS.slice(0,-1).map(time=><option key={time} value={time}>{time}</option>)}</select><span>–</span><select aria-label={`${label}, završetak rada`} disabled={!d.enabled} value={d.end} onChange={e=>onChange({...value,[String(index)]:{...d,end:e.target.value}})}>{TIME_OPTIONS.filter(time=>time>d.start).map(time=><option key={time} value={time}>{time}</option>)}</select><small>{d.enabled?"Radi":"Ne radi"}</small></div>})}<footer><button type="button" className="primary" onClick={onSave}>Spremi radno vrijeme</button><button type="button" onClick={onCancel}>Odustani</button></footer></div>}

export function Clinics(){
  const clinics=useApi<Clinic[]>("/api/clinics?include_hidden=true",[]);const rooms=useApi<Room[]>("/api/rooms?include_hidden=true",[]);const providers=useApi<Provider[]>("/api/providers?include_hidden=true",[]);
  const [tab,setTab]=useState<"clinics"|"staff">("clinics");const [query,setQuery]=useState("");const [selectedClinicId,setSelectedClinicId]=useState<number|null>(null);const [form,setForm]=useState<"clinic"|"room"|"staff"|null>(null);
  const [clinicName,setClinicName]=useState("");const [roomDraft,setRoomDraft]=useState({name:"",type:"ordinacija"});const [staff,setStaff]=useState({full_name:"",specialty:"",email:"",staff_role:"physician",clinic_id:""});const [week,setWeek]=useState(defaultWeek());
  const [scheduleProviderId,setScheduleProviderId]=useState<number|null>(null);const [scheduleWeek,setScheduleWeek]=useState<Record<string,DaySchedule>>(defaultWeek());
  const visibleClinics=useMemo(()=>clinics.data.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())),[clinics.data,query]);const selectedClinic=clinics.data.find(c=>c.id===selectedClinicId);
  async function addClinic(e:FormEvent){e.preventDefault();const created=await api<Clinic>("/api/clinics",{method:"POST",body:JSON.stringify({name:clinicName})});clinics.setData([...clinics.data,created].sort((a,b)=>a.name.localeCompare(b.name)));setSelectedClinicId(created.id);setClinicName("");setForm(null)}
  async function addRoom(e:FormEvent){e.preventDefault();if(!selectedClinicId)return;const created=await api<Room>("/api/rooms",{method:"POST",body:JSON.stringify({...roomDraft,clinic_id:selectedClinicId})});rooms.setData([...rooms.data,created]);setRoomDraft({name:"",type:"ordinacija"});setForm(null)}
  async function addStaff(e:FormEvent){e.preventDefault();const enabled=Object.values(week).find(d=>d.enabled);const created=await api<Provider>("/api/providers",{method:"POST",body:JSON.stringify({...staff,specialty:staff.specialty.trim()||null,clinic_id:Number(staff.clinic_id),work_start:enabled?.start??"07:00",work_end:enabled?.end??"15:00",weekly_working_hours:week})});providers.setData([...providers.data,created].sort((a,b)=>a.full_name.localeCompare(b.full_name)));setStaff({full_name:"",specialty:"",email:"",staff_role:"physician",clinic_id:""});setWeek(defaultWeek());setForm(null)}
  async function toggleClinic(x:Clinic){const u=await api<Clinic>(`/api/clinics/${x.id}/visibility`,{method:"POST"});clinics.setData(clinics.data.map(i=>i.id===u.id?u:i))}async function removeClinic(x:Clinic){if(!confirm(`Jeste li sigurni da želite obrisati kliniku „${x.name}“?`))return;await api(`/api/clinics/${x.id}`,{method:"DELETE"});clinics.setData(clinics.data.filter(i=>i.id!==x.id));rooms.setData(rooms.data.filter(r=>r.clinic_id!==x.id));setSelectedClinicId(null)}
  async function toggleRoom(x:Room){const u=await api<Room>(`/api/rooms/${x.id}/visibility`,{method:"POST"});rooms.setData(rooms.data.map(i=>i.id===u.id?u:i))}async function removeRoom(x:Room){if(!confirm(`Jeste li sigurni da želite obrisati prostoriju „${x.name}“?`))return;await api(`/api/rooms/${x.id}`,{method:"DELETE"});rooms.setData(rooms.data.filter(i=>i.id!==x.id))}
  async function toggleProvider(x:Provider){const u=await api<Provider>(`/api/providers/${x.id}/availability`,{method:"POST"});providers.setData(providers.data.map(i=>i.id===u.id?u:i))}async function removeProvider(x:Provider){if(!confirm(`Jeste li sigurni da želite obrisati osobu „${x.full_name}“? Povijesni termini ostaju sačuvani.`))return;await api(`/api/providers/${x.id}`,{method:"DELETE"});providers.setData(providers.data.filter(i=>i.id!==x.id))}
  function editSchedule(x:Provider){setScheduleProviderId(x.id);setScheduleWeek(x.weekly_working_hours??defaultWeek())}async function saveSchedule(){if(!scheduleProviderId)return;const u=await api<Provider>(`/api/providers/${scheduleProviderId}/schedule`,{method:"PATCH",body:JSON.stringify({weekly_working_hours:scheduleWeek})});providers.setData(providers.data.map(i=>i.id===u.id?u:i));setScheduleProviderId(null)}

  return <section className="page clinic-admin-page"><header className="page-header"><div><h1>Klinike</h1><p>Organizacija klinika, prostorija i osoblja.</p></div></header><nav className="resource-tabs" aria-label="Klinike i osoblje"><button className={tab==="clinics"?"active":""} onClick={()=>{setTab("clinics");setForm(null)}}>Klinike</button><button className={tab==="staff"?"active":""} onClick={()=>{setTab("staff");setForm(null)}}>Osoblje</button></nav>
  {tab==="clinics"?<div className="resource-master-detail clinics-only"><section className="resource-pane"><header><div><span className="eyebrow">Popis</span><h2>Klinike</h2></div><button className="primary" onClick={()=>setForm(form==="clinic"?null:"clinic")}>Dodaj</button></header><div className="clinic-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pretraži prema imenu klinike"/></div>{form==="clinic"&&<form className="compact-resource-form" onSubmit={addClinic}><input required value={clinicName} onChange={e=>setClinicName(e.target.value)} placeholder="Naziv nove klinike"/><button className="primary">Spremi kliniku</button></form>}<div className="clinic-navigator">{visibleClinics.map(c=><article className={`${selectedClinicId===c.id?"selected":""} ${c.visible_in_catalog===false?"resource-hidden":""}`} key={c.id}><button className="clinic-select" onClick={()=>setSelectedClinicId(c.id)}><Building2 size={17}/><strong>{c.name}</strong><span>{rooms.data.filter(r=>r.clinic_id===c.id).length}</span></button><div className="resource-line-actions"><button title="Sakrij/prikaži kliniku" onClick={()=>toggleClinic(c)}>{c.visible_in_catalog===false?<Eye size={15}/>:<EyeOff size={15}/>}</button><button className="danger-icon" title="Obriši kliniku" onClick={()=>removeClinic(c)}><Trash2 size={15}/></button></div></article>)}</div></section><section className="resource-pane"><header><div><span className="eyebrow">{selectedClinic?.name??"Odaberite kliniku"}</span><h2>Prostorije klinike</h2></div>{selectedClinic&&<button className="primary" onClick={()=>setForm(form==="room"?null:"room")}>Dodaj</button>}</header>{!selectedClinic&&<p className="resource-empty">Kliknite kliniku kako biste prikazali njezine prostorije.</p>}{selectedClinic&&<>{form==="room"&&<form className="compact-resource-form" onSubmit={addRoom}><input required value={roomDraft.name} onChange={e=>setRoomDraft({...roomDraft,name:e.target.value})} placeholder="Ime prostorije"/><input value={roomDraft.type} onChange={e=>setRoomDraft({...roomDraft,type:e.target.value})} placeholder="Vrsta prostorije"/><button className="primary">Spremi prostoriju</button></form>}<div className="room-detail-list">{rooms.data.filter(r=>r.clinic_id===selectedClinic.id).map(r=><article className={r.visible_in_catalog===false?"resource-hidden":""} key={r.id}><div><DoorOpen size={17}/><span><strong>{r.name}</strong><small>{r.type}</small></span></div><div className="resource-line-actions"><button title="Sakrij/prikaži prostoriju" onClick={()=>toggleRoom(r)}>{r.visible_in_catalog===false?<Eye size={15}/>:<EyeOff size={15}/>}</button><button className="danger-icon" title="Obriši prostoriju" onClick={()=>removeRoom(r)}><Trash2 size={15}/></button></div></article>)}</div></>}</section></div>
  :<section className="resource-pane staff-only"><header><div><span className="eyebrow">Tim</span><h2>Osoblje</h2></div><button className="primary" onClick={()=>setForm(form==="staff"?null:"staff")}>Dodaj osobu</button></header>{form==="staff"&&<form className="staff-week-form" onSubmit={addStaff}><div className="form-grid"><label>Uloga<select value={staff.staff_role} onChange={e=>setStaff({...staff,staff_role:e.target.value,specialty:e.target.value==="physician"?staff.specialty:""})}><option value="physician">Liječnik</option><option value="nurse">Medicinska sestra/tehničar</option><option value="secretary">Tajnik/administrator</option></select></label><label>Klinika<select required value={staff.clinic_id} onChange={e=>setStaff({...staff,clinic_id:e.target.value})}><option value="">Odaberi kliniku</option>{clinics.data.filter(c=>c.visible_in_catalog!==false).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Ime i prezime<input required value={staff.full_name} onChange={e=>setStaff({...staff,full_name:e.target.value})}/></label><label>E-mail<input required type="email" value={staff.email} onChange={e=>setStaff({...staff,email:e.target.value})}/></label><label>Specijalnost / radno mjesto<input required={staff.staff_role==="physician"} value={staff.specialty} onChange={e=>setStaff({...staff,specialty:e.target.value})}/></label></div><WeekEditor value={week} onChange={setWeek} onSave={()=>undefined} onCancel={()=>setForm(null)}/><button className="primary">Spremi osobu</button></form>}<div className="staff-roster">{providers.data.map(p=><div className="staff-roster-item" key={p.id}><article className={p.available_for_work===false?"resource-hidden":""}><div className="staff-avatar"><UserRoundCog size={17}/></div><div><strong>{p.full_name}</strong><span>{roleLabel(p.staff_role)}{p.specialty?` · ${p.specialty}`:""} · {clinics.data.find(c=>c.id===p.clinic_id)?.name??"Bez klinike"}</span><small><Mail size={12}/>{p.email||"E-mail nije upisan"}</small></div><div className="staff-week-summary">{DAYS.map((_,day)=>p.weekly_working_hours?.[String(day)]?.enabled?<b key={day}>{day+1}</b>:<i key={day}>{day+1}</i>)}</div><div className="resource-line-actions"><button title="Promijeni radno vrijeme" onClick={()=>editSchedule(p)}><Clock3 size={16}/></button><button title={p.available_for_work===false?"Označi da osoba radi":"Označi da osoba ne radi"} onClick={()=>toggleProvider(p)}>{p.available_for_work===false?<Eye size={16}/>:<EyeOff size={16}/>}</button><button className="danger-icon" title="Obriši osobu" onClick={()=>removeProvider(p)}><Trash2 size={16}/></button></div></article>{scheduleProviderId===p.id&&<WeekEditor value={scheduleWeek} onChange={setScheduleWeek} onSave={saveSchedule} onCancel={()=>setScheduleProviderId(null)}/>}</div>)}</div></section>}
  </section>;
}
