import { FormEvent, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { ActionButton } from "../components/ActionButton";
import { HelpHint } from "../components/HelpHint";
import { useApi } from "../hooks/useApi";
import { KnowledgeProtocol } from "../types";

export function KnowledgeProtocols() {
  const protocols = useApi<KnowledgeProtocol[]>("/api/knowledge-protocols", []);
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState({ key: "", title: "", specialty: "", version: "1.0", summary: "", source_title: "", source_url: "", rule_label: "", condition_text: "", guidance_text: "", evidence_level: "" });
  async function create(event: FormEvent) { event.preventDefault(); const { rule_label, condition_text, guidance_text, evidence_level, ...protocol } = draft; const item = await api<KnowledgeProtocol>("/api/knowledge-protocols", { method: "POST", body: JSON.stringify({ ...protocol, rules: [{ label: rule_label, condition_text, guidance_text, evidence_level: evidence_level || null }] }) }); protocols.setData([...protocols.data, item]); setOpen(false); }
  return <div className="page knowledge-page"><header className="page-header"><div><span className="eyebrow">Dokaz prije zaključka</span><h1>Klinička knjižnica</h1><p>Verzionirani protokoli s obaveznim izvorom i liječničkim pregledom. Ne primjenjuju se automatski na pacijente.</p></div><ActionButton variant="create" onClick={() => setOpen(!open)} helpTitle="Novi protokol" help="Stvara draft. Draft nije služben dok ga liječnik ne pregleda.">Novi protokol</ActionButton></header>
  {open && <form className="panel form-grid" onSubmit={create}><h2>Novi draft <HelpHint title="Sigurnosna granica">Unesite samo sadržaj iz provjerljivog HTTPS izvora. Protokol ne donosi odluku umjesto liječnika.</HelpHint></h2><label>Ključ<input required pattern="[a-z0-9_-]+" value={draft.key} onChange={e => setDraft({...draft,key:e.target.value})}/></label><label>Naziv<input required value={draft.title} onChange={e => setDraft({...draft,title:e.target.value})}/></label><label>Područje<input required value={draft.specialty} onChange={e => setDraft({...draft,specialty:e.target.value})}/></label><label>Verzija<input required value={draft.version} onChange={e => setDraft({...draft,version:e.target.value})}/></label><label className="wide-field">Sažetak<textarea required value={draft.summary} onChange={e => setDraft({...draft,summary:e.target.value})}/></label><label>Naziv izvora<input required value={draft.source_title} onChange={e => setDraft({...draft,source_title:e.target.value})}/></label><label>HTTPS izvor<input required type="url" value={draft.source_url} onChange={e => setDraft({...draft,source_url:e.target.value})}/></label><label>Naziv pravila<input required value={draft.rule_label} onChange={e => setDraft({...draft,rule_label:e.target.value})}/></label><label>Razina dokaza<input value={draft.evidence_level} onChange={e => setDraft({...draft,evidence_level:e.target.value})}/></label><label className="wide-field">Kada razmotriti<textarea required value={draft.condition_text} onChange={e => setDraft({...draft,condition_text:e.target.value})}/></label><label className="wide-field">Referentna smjernica<textarea required value={draft.guidance_text} onChange={e => setDraft({...draft,guidance_text:e.target.value})}/></label><ActionButton type="submit" variant="create" helpTitle="Spremi draft" help="Sprema neslužbeni draft za liječnički pregled.">Spremi draft</ActionButton></form>}
  <section className="knowledge-shelf">{protocols.data.map(item => <Link to={`/knowledge/${item.id}`} className="knowledge-protocol-card" key={item.id}><span>{item.specialty} · v{item.version}</span><h2>{item.title}</h2><p>{item.summary}</p><footer><strong className={`knowledge-state ${item.status}`}>{item.status}</strong><span>{item.rules.length} pravila</span></footer></Link>)}</section></div>;
}
