import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api/client";
import { DateInput } from "../components/DateInput";
import { useApi } from "../hooks/useApi";
import type { Patient, Provider, Room, Service } from "../types";

type PackageItem = { id: number; service_id: number; activity_key: string; activity_kind: string; sequence: number; duration_minutes: number; required: boolean; preparation_requirements: Array<{ label: string }> };
type PackageVersion = { id: number; version: number; status: string; items: PackageItem[] };
type Package = { id: number; name: string; description: string | null; versions: PackageVersion[] };
type Assignment = { package_item_id: number; date: string; start_time: string; end_time: string; provider_id: string; room_id: string };
function addMinutes(time: string, minutes: number) { const [h, m] = time.split(":").map(Number); const total = h * 60 + m + minutes; return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`; }

export function PackageBooking() {
  const navigate = useNavigate(); const packages = useApi<Package[]>("/api/service-packages", []); const services = useApi<Service[]>("/api/services", []); const providers = useApi<Provider[]>("/api/providers", []); const rooms = useApi<Room[]>("/api/rooms", []);
  const [query, setQuery] = useState(""); const patients = useApi<Patient[]>(query.length >= 2 ? `/api/patients?q=${encodeURIComponent(query)}` : "/api/patients?q=__none__", []); const [patient, setPatient] = useState<Patient | null>(null);
  const [versionId, setVersionId] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [start, setStart] = useState("08:00"); const [assignments, setAssignments] = useState<Assignment[]>([]); const [preview, setPreview] = useState<any>(null); const [confirm, setConfirm] = useState(false); const [error, setError] = useState(""); const [idempotencyKey, setIdempotencyKey] = useState(() => crypto.randomUUID());
  const version = useMemo(() => packages.data.flatMap(item => item.versions).find(item => String(item.id) === versionId), [packages.data, versionId]);
  const selectedPackage = useMemo(() => packages.data.find(item => item.versions.some(version => String(version.id) === versionId)), [packages.data, versionId]);
  const estimatedPrice = useMemo(() => version?.items.reduce((sum, item) => sum + Number(services.data.find(service => service.id === item.service_id)?.price ?? 0), 0) ?? 0, [version, services.data]);
  function buildAssignments(selected: PackageVersion, startAt: string) { let cursor = startAt; return [...selected.items].sort((a,b)=>a.sequence-b.sequence).map(item => { const end = addMinutes(cursor, item.duration_minutes); const row = { package_item_id: item.id, date, start_time: cursor, end_time: end, provider_id: "", room_id: "" }; cursor = addMinutes(end, 10); return row; }); }
  function chooseVersion(id: string) { setVersionId(id); const selected = packages.data.flatMap(item => item.versions).find(item => String(item.id) === id); setAssignments(selected ? buildAssignments(selected, start) : []); setPreview(null); setIdempotencyKey(crypto.randomUUID()); }
  function update(index: number, patch: Partial<Assignment>) { setAssignments(rows => rows.map((row, position) => position === index ? { ...row, ...patch } : row)); setPreview(null); }
  async function check() { if (!patient || !version) return; setError(""); try { setPreview(await api(`/api/service-package-versions/${version.id}/schedule-preview`, { method: "POST", body: JSON.stringify({ patient_id: patient.id, assignments: assignments.map(row => ({ ...row, provider_id: Number(row.provider_id), room_id: Number(row.room_id) })) }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Provjera nije uspjela."); } }
  async function book() { if (!patient || !version) return; const result = await api<{journey_id:number}>(`/api/service-package-versions/${version.id}/book`, { method: "POST", body: JSON.stringify({ patient_id: patient.id, idempotency_key: idempotencyKey, assignments: assignments.map(row => ({ ...row, provider_id: Number(row.provider_id), room_id: Number(row.room_id) })) }) }); navigate(`/journeys/${result.journey_id}`); }
  return <section className="page package-booking"><div className="page-header"><div><span className="eyebrow">Jedan koordinirani dolazak</span><h1>Naruči paket usluga</h1><p>Prije spremanja provjerite svaku aktivnost, prostoriju i liječnika.</p></div></div>
    <div className="package-booking-grid"><label>Pacijent<input value={query} onChange={event => { setQuery(event.target.value); setPatient(null); setIdempotencyKey(crypto.randomUUID()); }} placeholder="Pretraži pacijenta"/></label>{query.length >= 2 && !patient && <div className="patient-results">{patients.data.map(item => <button key={item.id} onClick={() => { setPatient(item); setQuery(`${item.first_name} ${item.last_name}`); setIdempotencyKey(crypto.randomUUID()); }}>{item.first_name} {item.last_name}</button>)}</div>}<label>Paket<select value={versionId} onChange={event => chooseVersion(event.target.value)}><option value="">Odaberite objavljeni paket</option>{packages.data.map(item => item.versions.filter(version => version.status === "published").map(version => <option key={version.id} value={version.id}>{item.name} · v{version.version}</option>))}</select></label><label>Datum<DateInput value={date} onChange={value => { setDate(value); setAssignments(rows => rows.map(row => ({ ...row, date: value }))); setPreview(null); }}/></label><label>Početak<input type="time" value={start} onChange={event => { setStart(event.target.value); if (version) setAssignments(buildAssignments(version, event.target.value)); setPreview(null); }}/></label></div>
    {version && <section className="journey-panel"><h2>{selectedPackage?.name ?? "Aktivnosti paketa"}</h2>{selectedPackage?.description && <p>{selectedPackage.description}</p>}{assignments.map((row, index) => { const item = version.items.find(item => item.id === row.package_item_id)!; const service = services.data.find(service => service.id === item.service_id); return <article className="package-activity-row" key={row.package_item_id}><b>{item.sequence}. {service?.name ?? item.activity_key}</b><span>{item.duration_minutes} min · {item.required ? "obvezno" : "neobvezno"} · {row.start_time}–{row.end_time}</span>{item.preparation_requirements?.length > 0 && <small>Priprema: {item.preparation_requirements.map(requirement => requirement.label).join(", ")}</small>}<label>Liječnik<select value={row.provider_id} onChange={event => update(index, { provider_id: event.target.value })}><option value="">Odaberite</option>{providers.data.filter(item => item.staff_role === "physician").map(item => <option value={item.id} key={item.id}>{item.full_name}</option>)}</select></label><label>Prostorija<select value={row.room_id} onChange={event => update(index, { room_id: event.target.value })}><option value="">Odaberite</option>{rooms.data.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{preview?.activities?.[index]?.conflicts?.map((conflict:string)=><small className="inline-error" key={conflict}>{conflict}</small>)}</article>; })}<p>Ukupno trajanje dolaska: <strong>{preview?.total_visit_duration_minutes ?? "provjerite raspored"} min</strong> · procijenjena cijena: <strong>{estimatedPrice.toFixed(2)} EUR</strong></p>{preview?.warnings?.map((warning:string)=><p className="inline-error" key={warning}>{warning}</p>)}{error && <p className="inline-error">{error}</p>}<footer><button onClick={check} disabled={!patient || assignments.some(row => !row.provider_id || !row.room_id)}>Provjeri raspored</button><button className="primary" disabled={!preview?.valid} onClick={() => setConfirm(true)}>Naruči paket</button></footer></section>}
    {confirm && <div className="modal-backdrop"><section className="modal-panel" role="dialog" aria-modal="true"><header><h2>Potvrdi koordinirani dolazak</h2></header><p>Stvorit će se jedan dolazak i {assignments.length} odvojenih aktivnosti. Ako bilo koja rezervacija ne uspije, ništa se neće spremiti.</p><footer><button onClick={() => setConfirm(false)}>Odustani</button><button className="primary" onClick={book}>Potvrdi naručivanje</button></footer></section></div>}
  </section>;
}
