"""Generate lightweight TypeScript types from the FastAPI OpenAPI schema.

This intentionally avoids a Node/OpenAPI generator dependency.  It is a narrow
contract guard for frontend DTO typing: the backend remains the source of truth,
and CI can run this script with --check to detect stale generated types.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "frontend" / "src" / "api" / "generated-openapi.ts"


def load_openapi() -> dict[str, Any]:
  sys.path.insert(0, str(BACKEND))
  from app.main import app  # noqa: PLC0415

  return app.openapi()


def type_name(name: str) -> str:
  cleaned = re.sub(r"[^0-9A-Za-z_]", "_", name)
  if re.match(r"^[0-9]", cleaned):
    cleaned = f"Schema_{cleaned}"
  return cleaned


def property_name(name: str) -> str:
  if re.match(r"^[A-Za-z_$][0-9A-Za-z_$]*$", name):
    return name
  return repr(name)


def literal(value: Any) -> str:
  if value is None:
    return "null"
  if isinstance(value, bool):
    return "true" if value else "false"
  if isinstance(value, (int, float)):
    return str(value)
  return repr(str(value))


def schema_to_ts(schema: dict[str, Any] | bool | None, schemas: dict[str, Any]) -> str:
  if schema is True or schema is None:
    return "unknown"
  if schema is False:
    return "never"
  if "$ref" in schema:
    return type_name(schema["$ref"].rsplit("/", 1)[-1])
  if "const" in schema:
    return literal(schema["const"])
  if "enum" in schema:
    values = schema.get("enum") or []
    return " | ".join(literal(value) for value in values) or "unknown"
  if "anyOf" in schema:
    return " | ".join(schema_to_ts(item, schemas) for item in schema["anyOf"])
  if "oneOf" in schema:
    return " | ".join(schema_to_ts(item, schemas) for item in schema["oneOf"])
  if "allOf" in schema:
    return " & ".join(schema_to_ts(item, schemas) for item in schema["allOf"])

  schema_type = schema.get("type")
  if isinstance(schema_type, list):
    return " | ".join(schema_to_ts({**schema, "type": item}, schemas) for item in schema_type)
  if schema_type == "string":
    return "string"
  if schema_type == "null":
    return "null"
  if schema_type in {"integer", "number"}:
    return "number"
  if schema_type == "boolean":
    return "boolean"
  if schema_type == "array":
    return f"Array<{schema_to_ts(schema.get('items'), schemas)}>"
  if schema_type == "object" or "properties" in schema:
    return object_to_ts(schema, schemas)
  return "unknown"


def object_to_ts(schema: dict[str, Any], schemas: dict[str, Any]) -> str:
  properties = schema.get("properties") or {}
  required = set(schema.get("required") or [])
  parts: list[str] = ["{"]
  for name, prop_schema in sorted(properties.items()):
    optional = "" if name in required else "?"
    parts.append(f"  {property_name(name)}{optional}: {schema_to_ts(prop_schema, schemas)};")
  additional = schema.get("additionalProperties")
  if additional and additional is not False:
    parts.append(f"  [key: string]: {schema_to_ts(additional, schemas)};")
  parts.append("}")
  return "\n".join(parts)


def render(openapi: dict[str, Any]) -> str:
  schemas = openapi.get("components", {}).get("schemas", {})
  lines = [
    "/* eslint-disable */",
    "/* Generated by scripts/generate_openapi_types.py. Do not edit manually. */",
    "",
  ]
  for name in sorted(schemas):
    lines.append(f"export type {type_name(name)} = {schema_to_ts(schemas[name], schemas)};")
    lines.append("")
  return "\n".join(lines).rstrip() + "\n"


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--check", action="store_true", help="fail if generated file is stale")
  args = parser.parse_args()

  content = render(load_openapi())
  if args.check:
    existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if existing != content:
      diff = "\n".join(difflib.unified_diff(
        existing.splitlines(),
        content.splitlines(),
        fromfile=str(OUTPUT),
        tofile="generated",
        lineterm="",
      ))
      print(diff)
      return 1
    return 0
  OUTPUT.parent.mkdir(parents=True, exist_ok=True)
  OUTPUT.write_text(content, encoding="utf-8")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
